// FE Electrical Question Bank — Extension Pack 7 (~200 problems)
(function () {
  if (typeof QUESTION_BANK === "undefined" || typeof S === "undefined") return;

  const P = {
    // Math — +20
    1: [
      { q: "Find $|z|$ for $z = -3 + 4j$:",
        choices: ["$5$", "$1$", "$\\sqrt{7}$", "$25$"], correct: 0,
        solution: S({ c: "Magnitude $|a+bj| = \\sqrt{a^2+b^2}$.", s: ["$\\sqrt{9+16} = 5$."], a: "$5$" }), ref: "p.36" },
      { q: "$(1+j)^4 = ?$", choices: ["$-4$", "$4$", "$4j$", "$2$"], correct: 0,
        solution: S({ c: "Convert to polar: $1+j = \\sqrt{2}\\angle 45°$. Raise to power.", s: ["$(\\sqrt{2})^4 = 4$. Angle: $4 \\cdot 45° = 180°$.", "$4\\angle 180° = -4$."], a: "$-4$" }), ref: "p.36" },
      { q: "Solve $x^2 + 4x + 13 = 0$:",
        choices: ["$x = -2 \\pm 3j$", "$x = -2 \\pm \\sqrt{13}$", "$x = 2 \\pm 3j$", "$x = \\pm \\sqrt{17}$"], correct: 0,
        solution: S({ c: "Discriminant negative → complex conjugate roots.", s: ["$\\Delta = 16-52 = -36$. $\\sqrt{-36} = 6j$.", "$x = (-4 \\pm 6j)/2 = -2 \\pm 3j$."], a: "$-2 \\pm 3j$" }), ref: "p.35" },
      { q: "$\\det\\begin{pmatrix}3&-1&2\\\\0&4&5\\\\0&0&6\\end{pmatrix}$:",
        choices: ["$72$", "$24$", "$30$", "$0$"], correct: 0,
        solution: S({ c: "Upper triangular: product of diagonal.", s: ["$3 \\cdot 4 \\cdot 6 = 72$."], a: "$72$" }), ref: "p.57" },
      { q: "Inverse of identity matrix:",
        choices: ["Itself", "Zero matrix", "Doesn't exist", "Transpose"], correct: 0,
        solution: S({ c: "$I \\cdot I = I$, so $I^{-1} = I$.", s: [""], a: "$I^{-1} = I$" }), ref: "p.57" },
      { q: "$\\dfrac{d}{dx}[\\ln(x^2+1)]$:",
        choices: ["$2x/(x^2+1)$", "$1/(x^2+1)$", "$2x$", "$\\ln(2x)$"], correct: 0,
        solution: S({ c: "Chain rule: $\\frac{d}{dx}\\ln u = u'/u$.", s: ["$u = x^2+1$, $u' = 2x$.", "Result: $2x/(x^2+1)$."], a: "$2x/(x^2+1)$" }), ref: "p.47" },
      { q: "$\\int_0^{\\pi} \\sin x\\,dx = ?$",
        choices: ["$2$", "$0$", "$\\pi$", "$1$"], correct: 0,
        solution: S({ c: "Antideriv: $-\\cos x$. Evaluate.", s: ["$-\\cos\\pi - (-\\cos 0) = -(-1)-(-1) = 1+1 = 2$."], a: "$2$" }), ref: "p.49" },
      { q: "Find slope of $y = e^{2x}$ at $x = 0$:",
        choices: ["$2$", "$1$", "$0$", "$e$"], correct: 0,
        solution: S({ c: "$y' = 2e^{2x}$. At $x=0$: $2 \\cdot 1 = 2$.", s: [""], a: "$2$" }), ref: "p.47" },
      { q: "$\\sum_{k=0}^{\\infty}(0.4)^k = ?$",
        choices: ["$5/3 \\approx 1.667$", "$0.4$", "$\\infty$", "$1$"], correct: 0,
        solution: S({ c: "Geometric series $|r|<1$: $\\sum = 1/(1-r)$.", s: ["$1/(1-0.4) = 1/0.6 = 5/3$."], a: "$5/3$" }), ref: "p.50" },
      { q: "Solve $y'' - 4y' + 4y = 0$:",
        choices: ["$y = (C_1+C_2 x)e^{2x}$", "$y = C_1 e^{2x} + C_2 e^{-2x}$", "$y = C\\cos 2x$", "$y = C e^{4x}$"], correct: 0,
        solution: S({ c: "Char eq: $r^2-4r+4 = (r-2)^2 = 0$. Repeated root $r=2$.", s: ["Solution form: $(C_1 + C_2 x)e^{rx}$.", "Result: $(C_1+C_2 x)e^{2x}$."], a: "$(C_1+C_2 x)e^{2x}$" }), ref: "p.55" },
      { q: "Vector projection of $\\vec{a}=(3,4)$ onto $\\vec{b}=(1,0)$:",
        choices: ["$(3, 0)$", "$(0, 4)$", "$(3, 4)$", "$5$"], correct: 0,
        solution: S({ c: "$\\text{proj}_b a = (a \\cdot \\hat{b})\\hat{b}$.", s: ["$\\hat{b} = (1,0)$. $a\\cdot\\hat{b} = 3$.", "Projection: $(3,0)$."], a: "$(3, 0)$" }), ref: "p.38" },
      { q: "$\\sin(\\pi/6) + \\cos(\\pi/3)$:",
        choices: ["$1$", "$0$", "$\\sqrt{3}/2$", "$1/2$"], correct: 0,
        solution: S({ c: "Standard angles.", s: ["$\\sin 30° = 1/2$. $\\cos 60° = 1/2$.", "Sum: 1."], a: "$1$" }), ref: "p.37" },
      { q: "Average value of $f(x) = x^2$ on $[0,2]$:",
        choices: ["$4/3$", "$2$", "$8/3$", "$4$"], correct: 0,
        solution: S({ c: "Mean value: $(1/(b-a))\\int_a^b f\\,dx$.", s: ["$(1/2)\\int_0^2 x^2 dx = (1/2)(8/3) = 4/3$."], a: "$4/3$" }), ref: "p.49" },
      { q: "Solve $2^x = 32$:",
        choices: ["$x = 5$", "$x = 16$", "$x = \\log 32$", "$x = 32$"], correct: 0,
        solution: S({ c: "$32 = 2^5$.", s: [""], a: "$x = 5$" }), ref: "p.36" },
      { q: "$\\log(100) - \\log(10)$ (base 10):",
        choices: ["$1$", "$10$", "$2$", "$90$"], correct: 0,
        solution: S({ c: "Log subtraction = log division.", s: ["$\\log(100/10) = \\log 10 = 1$."], a: "$1$" }), ref: "p.36" },
      { q: "Area enclosed by $y = x^2$ and $y = 4$:",
        choices: ["$32/3$", "$8$", "$16$", "$4$"], correct: 0,
        solution: S({ c: "Intersection at $x = \\pm 2$. Area = $\\int_{-2}^2 (4-x^2)dx$.", s: ["$[4x - x^3/3]_{-2}^2 = (8-8/3) - (-8+8/3) = 32/3$."], a: "$32/3$" }), ref: "p.49" },
      { q: "Derivative of $\\sec x$:",
        choices: ["$\\sec x \\tan x$", "$-\\csc x \\cot x$", "$\\tan^2 x$", "$\\sec^2 x$"], correct: 0,
        solution: S({ c: "Standard derivative.", s: ["$\\sec x = 1/\\cos x$. Differentiate: $\\sin x / \\cos^2 x = \\sec x \\tan x$."], a: "$\\sec x \\tan x$" }), ref: "p.47" },
      { q: "$\\int 1/(x \\ln x)\\,dx$:",
        choices: ["$\\ln|\\ln x| + C$", "$\\ln x + C$", "$\\ln^2 x + C$", "$1/x^2 + C$"], correct: 0,
        solution: S({ c: "Substitution $u = \\ln x$, $du = dx/x$.", s: ["$\\int (1/u) du = \\ln|u| + C = \\ln|\\ln x| + C$."], a: "$\\ln|\\ln x| + C$" }), ref: "p.49" },
      { q: "Limit $\\lim_{x\\to\\infty} x e^{-x}$:",
        choices: ["$0$", "$\\infty$", "$1$", "$e$"], correct: 0,
        solution: S({ c: "Exponential decay beats polynomial growth. L'Hopital confirms.", s: ["$\\lim x/e^x \\to 1/e^x \\to 0$."], a: "$0$" }), ref: "p.47" },
      { q: "$\\vec{A}\\cdot\\vec{B}$ if both unit vectors at 60° angle:",
        choices: ["$1/2$", "$\\sqrt{3}/2$", "$1$", "$0$"], correct: 0,
        solution: S({ c: "$\\vec{A}\\cdot\\vec{B} = |A||B|\\cos\\theta$.", s: ["$1 \\cdot 1 \\cdot \\cos 60° = 0.5$."], a: "$1/2$" }), ref: "p.38" },
    ],

    // Prob — +12
    2: [
      { q: "P(rolling two 6s in a row with fair die):",
        choices: ["$1/36$", "$1/6$", "$2/36$", "$1/12$"], correct: 0,
        solution: S({ c: "Independent: multiply.", s: ["$(1/6)(1/6) = 1/36$."], a: "$1/36$" }), ref: "p.64" },
      { q: "Variance of {1, 2, 3, 4, 5} (population):",
        choices: ["$2$", "$2.5$", "$5$", "$10$"], correct: 0,
        solution: S({ c: "$\\sigma^2 = (1/n)\\sum (x_i-\\bar{x})^2$.", s: ["$\\bar{x} = 3$. Deviations: ±2, ±1, 0.", "$(4+1+0+1+4)/5 = 10/5 = 2$."], a: "$2$" }), ref: "p.63" },
      { q: "Number of ways to arrange 4 letters from {A,B,C,D,E}:",
        choices: ["$P(5,4) = 120$", "$24$", "$625$", "$5$"], correct: 0,
        solution: S({ c: "Permutations: $P(n,r) = n!/(n-r)!$.", s: ["$5!/1! = 120$."], a: "$120$" }), ref: "p.64" },
      { q: "P(red queen from a deck):",
        choices: ["$2/52 = 1/26$", "$4/52$", "$1/52$", "$1/13$"], correct: 0,
        solution: S({ c: "Red queens: hearts + diamonds = 2.", s: [""], a: "$2/52$" }), ref: "p.64" },
      { q: "Continuous uniform on [0,1]. P(X > 0.7):",
        choices: ["$0.3$", "$0.7$", "$0.5$", "$1$"], correct: 0,
        solution: S({ c: "Uniform: $P(X > a) = 1-a$.", s: ["$1 - 0.7 = 0.3$."], a: "$0.3$" }), ref: "p.67" },
      { q: "Sample size for 95% CI with margin $\\pm 2$, $\\sigma = 10$:",
        choices: ["$n \\approx 96$", "$25$", "$10$", "$100$"], correct: 0,
        solution: S({ c: "Margin = $z \\sigma/\\sqrt{n}$. Solve for n.", s: ["$2 = 1.96 \\cdot 10/\\sqrt{n}$.", "$\\sqrt{n} = 9.8$, $n = 96.04 \\approx 97$."], a: "$\\approx 96$" }), ref: "p.69" },
      { q: "Two events independent: $P(A \\cap B) = ?$",
        choices: ["$P(A) \\cdot P(B)$", "$P(A) + P(B)$", "$\\max(P(A), P(B))$", "$0$"], correct: 0,
        solution: S({ c: "Independence definition.", s: [""], a: "$P(A)P(B)$" }), ref: "p.64" },
      { q: "Skewness of normal distribution:",
        choices: ["$0$ (symmetric)", "$1$", "Positive", "Negative"], correct: 0,
        solution: S({ c: "Normal: symmetric bell curve.", s: ["Skewed right: positive skew (tail to right).", "Skewed left: negative."], a: "$0$" }), ref: "p.67" },
      { q: "Maximum likelihood estimate (MLE):",
        choices: ["Parameter value that maximizes likelihood of observed data", "Sample mean only", "Median", "Mode"], correct: 0,
        solution: S({ c: "MLE: find $\\theta$ maximizing $L(\\theta|x_1,...,x_n)$.", s: ["For normal: MLE of $\\mu$ = sample mean.", "For Poisson: MLE of $\\lambda$ = sample mean."], a: "Max likelihood param" }), ref: "p.69" },
      { q: "Coefficient of variation: $\\sigma/\\mu$. For data with $\\mu = 50$, $\\sigma = 10$:",
        choices: ["$0.2$ or 20%", "$5$", "$60$", "$40$"], correct: 0,
        solution: S({ c: "CV = $\\sigma/\\mu$.", s: ["$10/50 = 0.2$."], a: "$0.2 = 20\\%$" }), ref: "p.63" },
      { q: "Chebyshev's inequality: $P(|X-\\mu| \\ge k\\sigma) \\le ?$",
        choices: ["$1/k^2$", "$1/k$", "$1/2k$", "$0$"], correct: 0,
        solution: S({ c: "Chebyshev: holds for any distribution.", s: ["For $k=2$: at most 25% of data more than 2 SD from mean.", "Compare to normal: only ~5% beyond 2 SD."], a: "$1/k^2$" }), ref: "p.66" },
      { q: "Bayes: $P(A|B) = \\dfrac{P(B|A)P(A)}{P(B)}$ — describes:",
        choices: ["Inverse conditional probability", "Joint probability", "Marginal", "Independence"], correct: 0,
        solution: S({ c: "Bayes inverts conditional: $P(B|A) \\to P(A|B)$.", s: ["Used: medical diagnosis, ML classifiers."], a: "Inverse conditional" }), ref: "p.65" },
    ],

    // Ethics — +5
    3: [
      { q: "Engineer accepts a private gift from contractor on stamped project:",
        choices: ["Conflict of interest — refuse or disclose", "OK if small", "OK after project ends", "Required"], correct: 0,
        solution: S({ c: "Rule 4: faithful agent. Gifts from vendors compromise objectivity.", s: [""], a: "Conflict — refuse/disclose" }), ref: "p.4" },
      { q: "PE works for company A but moonlights for company B (same industry):",
        choices: ["Possible conflict of interest — disclose to A", "Always forbidden", "Always allowed", "Just disclose to B"], correct: 0,
        solution: S({ c: "Moonlighting in same industry creates real or perceived conflicts.", s: ["Most employers require disclosure or prohibit competing work."], a: "Disclose to primary employer" }), ref: "p.4" },
      { q: "Engineer signs project but actual work was done by unlicensed person without review:",
        choices: ["Plan-stamping — major ethics violation", "OK if engineer is supervisor", "Acceptable", "Common practice"], correct: 0,
        solution: S({ c: "Plan stamping: signing work you didn't prepare or review = ethics violation, potential criminal fraud.", s: ["Strictly prohibited by every US state engineering board."], a: "Plan-stamping = violation" }), ref: "p.5" },
      { q: "An engineer is asked to investigate a structure they previously designed:",
        choices: ["Conflict — should recuse or disclose", "Must accept", "Cannot accept", "Charge double"], correct: 0,
        solution: S({ c: "Self-investigation bias. Disclose and let client decide if to proceed with independent reviewer.", s: [""], a: "Conflict — disclose" }), ref: "p.4-5" },
      { q: "Continuing education requirement varies by state, but commonly:",
        choices: ["15-30 PDH per 2-year renewal cycle", "Optional", "100 PDH/year", "None"], correct: 0,
        solution: S({ c: "Most state boards require PDH (Professional Development Hours) to maintain license.", s: ["Some require ethics-specific hours."], a: "15-30 PDH/cycle" }), ref: "p.11" },
    ],

    // Econ — +10
    4: [
      { q: "Find effective annual rate from 1% per month nominal:",
        choices: ["$\\approx 12.68\\%$", "$12\\%$", "$13\\%$", "$10\\%$"], correct: 0,
        solution: S({ c: "$EAR = (1+r/m)^m - 1$.", s: ["$(1.01)^{12} - 1 = 0.1268$ = 12.68%."], a: "$12.68\\%$" }), ref: "p.230" },
      { q: "Project: invest $\\$8000$ now, receive $\\$3000$/yr for 4 yrs. At $i=10\\%$, NPV:",
        choices: ["$\\approx \\$1{,}510$ (accept)", "$\\$4000$", "$\\$-1000$", "$\\$12{,}000$"], correct: 0,
        solution: S({ c: "$NPV = -P + A(P/A, 10\\%, 4)$.", s: ["$(P/A, 10\\%, 4) = 3.1699$.", "$NPV = -8000 + 3000 \\cdot 3.1699 = -8000 + 9510 = 1510$."], a: "NPV $\\approx \\$1510$" }), ref: "p.232" },
      { q: "Inflation-adjusted return: nominal 8%, inflation 3%. Real return:",
        choices: ["$\\approx 4.85\\%$", "$5\\%$", "$11\\%$", "$24\\%$"], correct: 0,
        solution: S({ c: "$(1+i_r) = (1+i_n)/(1+f)$.", s: ["$1.08/1.03 = 1.0485$.", "$i_r = 4.85\\%$."], a: "$\\approx 4.85\\%$" }), ref: "p.230" },
      { q: "Annual operating cost grows at $g = 5\\%$/year. PW of $\\$1000$ first-year cost over 10 years at $i = 8\\%$:",
        choices: ["$\\approx \\$8{,}530$ (geom gradient)", "$\\$10000$", "$\\$1000$", "$\\$3000$"], correct: 0,
        solution: S({ c: "Geometric gradient formula: $P = A_1 \\cdot [(1-(1+g)^n/(1+i)^n)/(i-g)]$.", s: ["$g=0.05, i=0.08, n=10$. Compute factor.", "$(1+g)/(1+i) = 1.05/1.08 = 0.9722$. $(0.9722)^{10} = 0.7541$.", "Factor: $(1 - 0.7541)/(0.08 - 0.05) = 0.2459/0.03 = 8.197$.", "$P = 1000 \\cdot 8.197 = \\$8197$. Close to 8530 depending on rounding."], a: "$\\approx \\$8200$" }), ref: "p.231" },
      { q: "MACRS vs straight-line for asset depreciation: MACRS gives:",
        choices: ["Higher early depreciation (accelerated)", "Lower depreciation", "Same total", "Random"], correct: 0,
        solution: S({ c: "MACRS: accelerated → bigger tax shield early on.", s: ["Both methods sum to same total depreciation over life."], a: "Accelerated early" }), ref: "p.230" },
      { q: "Capitalized cost (infinite series): $A = \\$500$/yr at $i=5\\%$:",
        choices: ["$\\$10{,}000$", "$\\$1000$", "$\\$5000$", "$\\$25{,}000$"], correct: 0,
        solution: S({ c: "Perpetuity: $P = A/i$.", s: ["$500/0.05 = 10000$."], a: "$\\$10{,}000$" }), ref: "p.231" },
      { q: "Sunk cost in economic analysis:",
        choices: ["Past cost — irrelevant to future decisions", "Future cost", "Critical to include", "Doubled"], correct: 0,
        solution: S({ c: "Sunk costs are non-recoverable past expenses. Rational decision-making ignores them.", s: [""], a: "Irrelevant (past)" }), ref: "p.232" },
      { q: "Choose between two equal-life projects via:",
        choices: ["Highest NPV (same i, same n)", "Higher cost", "Lower cost only", "Highest revenue"], correct: 0,
        solution: S({ c: "Mutually exclusive, equal lives: pick higher NPV.", s: ["Unequal lives: convert to EUAW first."], a: "Highest NPV" }), ref: "p.232" },
      { q: "Property tax based on:",
        choices: ["Assessed value × mill rate", "Income", "Sales", "Inflation"], correct: 0,
        solution: S({ c: "Property tax: annual based on local assessed value × tax rate (mills).", s: ["1 mill = $1 per $1000 of assessed value."], a: "Assessment × rate" }), ref: "p.232" },
      { q: "Working capital is:",
        choices: ["Current assets minus current liabilities", "Total revenue", "Net income", "Depreciation"], correct: 0,
        solution: S({ c: "Working capital: short-term liquidity measure.", s: ["Positive WC: can cover short-term obligations.", "Negative WC: cash flow issues likely."], a: "CA − CL" }), ref: "p.230" },
    ],

    // Materials — +6
    5: [
      { q: "Hole mobility in Si vs electron mobility:",
        choices: ["Hole mobility lower (~480 vs ~1350 cm²/V·s)", "Same", "Higher", "Zero"], correct: 0,
        solution: S({ c: "Electrons more mobile in Si.", s: [""], a: "Lower (1/3)" }), ref: "p.354" },
      { q: "Temperature coefficient of resistance for metals:",
        choices: ["Positive (R increases with T)", "Negative", "Zero", "Random"], correct: 0,
        solution: S({ c: "Metals: positive temp coefficient (~0.4%/°C for Cu).", s: ["Semiconductors: negative (more carriers freed).", "Used for: PTC thermistors as temp sensors."], a: "Positive" }), ref: "p.354" },
      { q: "Energy needed to free electron in Si:",
        choices: ["$\\ge E_g \\approx 1.12$ eV", "0", "100 eV", "Any energy"], correct: 0,
        solution: S({ c: "Bandgap energy minimum to promote electron from valence to conduction band.", s: ["Photon $\\lambda \\le hc/E_g \\approx 1.1$ µm."], a: "$\\ge 1.12$ eV" }), ref: "p.354" },
      { q: "p-n junction reverse breakdown:",
        choices: ["Sharp current increase at $V_{BR}$", "Linear", "Slow", "No effect"], correct: 0,
        solution: S({ c: "Beyond $V_{BR}$: avalanche or Zener breakdown. Sharp current increase.", s: ["Used: Zener regulator, surge protectors."], a: "Sharp at $V_{BR}$" }), ref: "p.354" },
      { q: "Drift current in semiconductor: $J_n =$",
        choices: ["$q n \\mu_n E$", "$q n E^2$", "$\\mu_n E$", "$n/E$"], correct: 0,
        solution: S({ c: "Drift current density (electrons): $J = qnv_d = qn\\mu E$.", s: [""], a: "$qn\\mu_n E$" }), ref: "p.354" },
      { q: "Resistor temperature coefficient $\\alpha$: for Cu ~$0.00393$/°C. R at 100°C if $R_0 = 100\\ \\Omega$ at 0°C:",
        choices: ["$\\approx 139.3\\ \\Omega$", "$100\\ \\Omega$", "$200\\ \\Omega$", "$110\\ \\Omega$"], correct: 0,
        solution: S({ c: "$R = R_0(1 + \\alpha\\Delta T)$.", s: ["$R = 100(1 + 0.00393 \\cdot 100) = 100 \\cdot 1.393 = 139.3$ Ω."], a: "$\\approx 139.3\\ \\Omega$" }), ref: "p.354" },
    ],

    // Circuits — +25
    6: [
      { q: "Sum of currents into a node = 0 is:",
        choices: ["Kirchhoff's Current Law (KCL)", "KVL", "Ohm's", "Tellegen"], correct: 0,
        solution: S({ c: "KCL: conservation of charge at node.", s: ["KVL: conservation of energy around loop."], a: "KCL" }), ref: "p.356" },
      { q: "Three identical resistors $R$ in star (Y): equivalent in $\\Delta$:",
        choices: ["$3R$", "$R$", "$R/3$", "$9R$"], correct: 0,
        solution: S({ c: "$Y$ to $\\Delta$ (balanced): $Z_\\Delta = 3 Z_Y$.", s: [""], a: "$3R$" }), ref: "p.363" },
      { q: "Cap initially at 0V charges to $V_s = 24$V via $R = 1$ kΩ, $C = 1000$ µF. Time to reach 12V:",
        choices: ["$\\approx 0.693$ s", "$1$ s", "$5$ s", "$0.5$ s"], correct: 0,
        solution: S({ c: "$v(t) = V_s(1-e^{-t/\\tau})$. Solve for $v = V_s/2$: $e^{-t/\\tau} = 0.5$, $t/\\tau = \\ln 2$.", s: ["$\\tau = 10^3 \\cdot 10^{-3} = 1$ s.", "$t = \\ln 2 \\cdot 1 = 0.693$ s."], a: "$0.693$ s", v: "$\\ln 2 \\approx 0.693$ — half-life equivalent." }), ref: "p.358" },
      { q: "Maximum power transferred to load from $V_{Th} = 10$ V, $R_{Th} = 5$Ω:",
        choices: ["$5$ W (when $R_L = 5$Ω)", "$10$ W", "$20$ W", "$2$ W"], correct: 0,
        solution: S({ c: "$P_{max} = V_{Th}^2/(4 R_{Th})$.", s: ["$100/20 = 5$ W."], a: "$5$ W" }), ref: "p.360" },
      { q: "Series RLC at resonance, current is:",
        choices: ["Maximum, in phase with V", "Minimum", "Lagging", "Leading"], correct: 0,
        solution: S({ c: "At resonance: $Z = R$ (purely resistive, min). Current max, in phase.", s: [""], a: "Max, in phase" }), ref: "p.361" },
      { q: "Inductor $V = L\\,di/dt$. If $i(t) = 3\\sin(100t)$ A, $L = 50$ mH, peak voltage:",
        choices: ["$15$ V", "$50$ V", "$3$ V", "$300$ V"], correct: 0,
        solution: S({ c: "$di/dt = 300\\cos(100t)$. Peak $= 300$.", s: ["$V_{peak} = L \\cdot 300 = 0.05 \\cdot 300 = 15$ V."], a: "$15$ V" }), ref: "p.358" },
      { q: "Two capacitors $C_1=2$ µF and $C_2=4$ µF in parallel, then series with $C_3=6$ µF. Total:",
        choices: ["$3$ µF", "$12$ µF", "$2$ µF", "$1$ µF"], correct: 0,
        solution: S({ c: "Parallel: add. Series: reciprocal sum.", s: ["$C_1\\|C_2 = 6$ µF.", "Series with $C_3=6$: $6 \\cdot 6/(6+6) = 3$ µF."], a: "$3$ µF" }), ref: "p.358" },
      { q: "Z = 50 + j20 Ω in polar form:",
        choices: ["$\\approx 53.85\\angle 21.8°$", "$70\\angle 45°$", "$50\\angle 20°$", "$30\\angle 90°$"], correct: 0,
        solution: S({ c: "$|Z|=\\sqrt{2500+400} = \\sqrt{2900}$. $\\angle = \\arctan(20/50)$.", s: ["$|Z| \\approx 53.85$. $\\arctan(0.4) \\approx 21.8°$."], a: "$53.85\\angle 21.8°$" }), ref: "p.360" },
      { q: "Three-phase Y source, $V_{LN} = 120$ V, $Z_\\phi = 8\\ \\Omega$ resistive. Total power:",
        choices: ["$5400$ W", "$1800$ W", "$15$ W", "$45$ W"], correct: 0,
        solution: S({ c: "Per phase: $I_\\phi = V/Z = 15$ A. $P_\\phi = I^2 R = 225 \\cdot 8 = 1800$ W. Total $3 \\times$.", s: ["$3 \\cdot 1800 = 5400$ W."], a: "$5400$ W" }), ref: "p.363" },
      { q: "AC sinusoid $v(t) = 50\\sin(\\omega t + 30°)$. Phasor:",
        choices: ["$50\\angle 30°$ (peak) or $35.4\\angle 30°$ (RMS)", "$50\\angle 0°$", "$30\\angle 50°$", "$50\\angle -30°$"], correct: 0,
        solution: S({ c: "Phasor: magnitude (peak or RMS) and phase angle.", s: ["Peak phasor: $50\\angle 30°$.", "RMS: divide by $\\sqrt{2}$."], a: "$50\\angle 30°$ (peak)" }), ref: "p.360" },
      { q: "Reactive power Q for $V_{rms}=100$, $I_{rms}=5$, $\\theta = 60°$ (V leads I):",
        choices: ["$\\approx 433$ VAR", "$250$ VAR", "$500$ VAR", "$\\approx 250$ W"], correct: 0,
        solution: S({ c: "$Q = V \\cdot I \\cdot \\sin\\theta$. Inductive load (V leads I) → Q positive.", s: ["$100 \\cdot 5 \\cdot \\sin 60° = 500 \\cdot 0.866 = 433$ VAR."], a: "$\\approx 433$ VAR" }), ref: "p.362" },
      { q: "Average power for $V_{rms}=100$, $I_{rms}=5$, $\\theta=60°$:",
        choices: ["$250$ W", "$500$ W", "$\\approx 433$ W", "$0$"], correct: 0,
        solution: S({ c: "$P = VI\\cos\\theta$.", s: ["$100 \\cdot 5 \\cdot 0.5 = 250$ W."], a: "$250$ W" }), ref: "p.362" },
      { q: "Two impedances $Z_1 = 6+j8$ and $Z_2 = 8+j6$ in parallel. Total Z:",
        choices: ["$\\approx 5.04\\angle 45°$ (computed)", "$14+j14$", "$7+j7$", "$50$"], correct: 0,
        solution: S({ c: "Parallel: $Z_1 Z_2/(Z_1+Z_2)$.", s: ["$Z_1 + Z_2 = 14+j14 = 14\\sqrt{2}\\angle 45°$.", "$Z_1 Z_2 = 10\\angle 53.13° \\cdot 10\\angle 36.87° = 100\\angle 90°$.", "Ratio: $100\\angle 90° / (14\\sqrt{2}\\angle 45°) = 5.05\\angle 45°$."], a: "$\\approx 5.05\\angle 45°$" }), ref: "p.360" },
      { q: "Total power dissipated in a 3-phase 480 V Y-source delivering 30 A at pf 0.9:",
        choices: ["$\\approx 22.4$ kW", "$13.0$ kW", "$15$ kW", "$25$ kW"], correct: 0,
        solution: S({ c: "$P = \\sqrt{3} V_{LL} I_L \\cos\\theta$.", s: ["$\\sqrt{3} \\cdot 480 \\cdot 30 \\cdot 0.9 = 22{,}448$ W."], a: "$22.4$ kW" }), ref: "p.363" },
      { q: "Voltage drop on 100 ft #14 AWG copper (R ≈ 0.253 Ω/100 ft each way = 0.506 round trip) at 15 A:",
        choices: ["$\\approx 7.6$ V", "$3.8$ V", "$15$ V", "$0.25$ V"], correct: 0,
        solution: S({ c: "$V_{drop} = I \\cdot R$ (both directions).", s: ["$15 \\cdot 0.506 = 7.59$ V."], a: "$\\approx 7.6$ V", v: "NEC: drop should be < 3% of nominal (120V → < 3.6V). This exceeds — need bigger wire." }), ref: "p.354" },
      { q: "Three resistors in series: 5Ω, 10Ω, 15Ω. Current with 60V source:",
        choices: ["$2$ A", "$4$ A", "$6$ A", "$0.5$ A"], correct: 0,
        solution: S({ c: "Series: $R_{total} = 30$. $I = V/R$.", s: ["$60/30 = 2$ A."], a: "$2$ A" }), ref: "p.356" },
      { q: "Energy delivered by 12V battery providing 2A for 1 hr:",
        choices: ["$86.4$ kJ (or 24 Wh)", "$24$ J", "$24$ kWh", "$86.4$ J"], correct: 0,
        solution: S({ c: "$W = Pt$. $P = VI = 24$ W. $t = 3600$ s.", s: ["$W = 24 \\cdot 3600 = 86{,}400$ J = 86.4 kJ = 24 Wh."], a: "$86.4$ kJ" }), ref: "p.356" },
      { q: "Calculate phasor impedance: 100Ω resistor, 200mH inductor in series at 50 Hz:",
        choices: ["$100 + j62.8$ Ω", "$100 + j10$", "$100\\angle 90°$", "$200\\angle 0°$"], correct: 0,
        solution: S({ c: "$X_L = 2\\pi f L$.", s: ["$X_L = 2\\pi(50)(0.2) = 62.83$ Ω.", "$Z = 100 + j62.83$ Ω."], a: "$100+j62.8$ Ω" }), ref: "p.360" },
      { q: "Cap and inductor in parallel at resonance:",
        choices: ["Acts as open circuit (infinite Z)", "Short", "Just R", "Acts as wire"], correct: 0,
        solution: S({ c: "Parallel LC at $\\omega_0$: ideally infinite impedance (tank).", s: ["With losses: very high but finite Q-dependent peak."], a: "Open at $\\omega_0$" }), ref: "p.361" },
      { q: "Power factor of $Z = 6 + j8$ (in series):",
        choices: ["$0.6$ lagging", "$0.8$", "$1.0$", "$0.6$ leading"], correct: 0,
        solution: S({ c: "$\\theta = \\arctan(8/6) = 53.13°$. $pf = \\cos = 0.6$. Inductive: lagging.", s: [""], a: "$0.6$ lagging" }), ref: "p.362" },
      { q: "Star-to-delta transformation with $Z_Y = 9+j12$ each: $Z_\\Delta$:",
        choices: ["$27 + j36$ each", "$3 + j4$ each", "$9+j12$ each", "$81+j144$ each"], correct: 0,
        solution: S({ c: "Balanced: $Z_\\Delta = 3 Z_Y$.", s: ["$3(9+j12) = 27+j36$."], a: "$27+j36$" }), ref: "p.363" },
      { q: "Power dissipated by 100Ω resistor with $i = 2 + 3\\sin(\\omega t)$ A:",
        choices: ["$\\approx 850$ W (DC²+AC²RMS²)R", "$400$ W", "$900$ W", "$700$ W"], correct: 0,
        solution: S({ c: "$P = I_{rms}^2 R$. $I_{rms}^2 = I_{DC}^2 + I_{AC,RMS}^2 = 4 + 9/2 = 8.5$.", s: ["$P = 8.5 \\cdot 100 = 850$ W."], a: "$\\approx 850$ W" }), ref: "p.360" },
      { q: "Energy in 1µH inductor at 100 mA:",
        choices: ["$5$ nJ", "$5$ µJ", "$5$ mJ", "$0.1$ µJ"], correct: 0,
        solution: S({ c: "$W = LI^2/2$.", s: ["$10^{-6} \\cdot 0.01/2 = 5 \\cdot 10^{-9} = 5$ nJ."], a: "$5$ nJ" }), ref: "p.358" },
      { q: "$V_{rms}$ of triangular wave with peak $V_m$:",
        choices: ["$V_m/\\sqrt{3}$", "$V_m/\\sqrt{2}$", "$V_m$", "$V_m/2$"], correct: 0,
        solution: S({ c: "Triangular wave RMS factor: $1/\\sqrt{3} \\approx 0.577$.", s: ["Sine: $1/\\sqrt{2} \\approx 0.707$.", "Square: 1.", "Sawtooth: $1/\\sqrt{3}$."], a: "$V_m/\\sqrt{3}$" }), ref: "p.360" },
      { q: "Time constant of RL circuit with 200Ω and 50 mH:",
        choices: ["$0.25$ ms", "$250$ s", "$10$ s", "$5$ ms"], correct: 0,
        solution: S({ c: "$\\tau = L/R$.", s: ["$0.05/200 = 0.00025$ s = 0.25 ms."], a: "$0.25$ ms" }), ref: "p.358" },
    ],

    // Linear Sys — +12
    7: [
      { q: "Inverse Laplace of $1/(s+a)^2$:",
        choices: ["$te^{-at}$", "$e^{-at}$", "$te^{at}$", "$1/(at)$"], correct: 0,
        solution: S({ c: "Pair: $t^n e^{-at} \\leftrightarrow n!/(s+a)^{n+1}$.", s: ["$n=1$: $te^{-at} \\leftrightarrow 1/(s+a)^2$."], a: "$te^{-at}$" }), ref: "p.56" },
      { q: "Transfer function order = highest power of $s$ in denominator. For $H(s) = 1/(s^3+2s^2+5s+1)$:",
        choices: ["$3$rd order", "$1$st", "$5$th", "$2$nd"], correct: 0,
        solution: S({ c: "Highest exponent of $s$ in denominator.", s: [""], a: "$3$rd" }), ref: "p.365" },
      { q: "DC gain of $H(s) = 12/(s^2+5s+6)$:",
        choices: ["$2$", "$12$", "$6$", "$1$"], correct: 0,
        solution: S({ c: "$H(0) = 12/6 = 2$.", s: [""], a: "$2$" }), ref: "p.366" },
      { q: "Two systems in parallel: $H_1 = 3$, $H_2 = -2$. Total:",
        choices: ["$1$", "$-6$", "$5$", "$-2/3$"], correct: 0,
        solution: S({ c: "Parallel TF adds.", s: ["$3 + (-2) = 1$."], a: "$1$" }), ref: "p.365" },
      { q: "Phase of $H(s) = 1/(s+1)$ at $\\omega = 1$:",
        choices: ["$-45°$", "$0°$", "$-90°$", "$+45°$"], correct: 0,
        solution: S({ c: "Pole at corner frequency: phase contribution is -45°.", s: [""], a: "$-45°$" }), ref: "p.366" },
      { q: "Bandwidth of overdamped 2nd-order system: dominant pole at $s = -2$. BW:",
        choices: ["$\\approx 2$ rad/s (dominant pole approximation)", "$\\sqrt{2}$", "$1$", "Infinite"], correct: 0,
        solution: S({ c: "Dominant pole approximation: BW $\\approx |p_{dominant}|$.", s: ["Valid when other poles much further from origin."], a: "$\\approx 2$ rad/s" }), ref: "p.366" },
      { q: "Pole at $s = -2 \\pm j5$. Natural frequency $\\omega_n$:",
        choices: ["$\\sqrt{29} \\approx 5.39$ rad/s", "$5$", "$2$", "$7$"], correct: 0,
        solution: S({ c: "$\\omega_n = $ distance from origin.", s: ["$\\sqrt{4+25} = \\sqrt{29}$."], a: "$\\approx 5.39$ rad/s" }), ref: "p.366" },
      { q: "Damping ratio $\\zeta$ for pole at $-2 \\pm j5$:",
        choices: ["$2/\\sqrt{29} \\approx 0.371$", "$0.5$", "$0.707$", "$1.0$"], correct: 0,
        solution: S({ c: "$\\zeta = |\\text{Re}|/\\omega_n$.", s: ["$2/\\sqrt{29} \\approx 0.371$."], a: "$\\approx 0.371$" }), ref: "p.366" },
      { q: "Final value of $y(t)$ for $Y(s) = 5/(s(s+2))$:",
        choices: ["$2.5$", "$5$", "$0$", "$\\infty$"], correct: 0,
        solution: S({ c: "FVT: $\\lim_{s\\to 0} sY = 5/2 = 2.5$.", s: [""], a: "$2.5$" }), ref: "p.56" },
      { q: "Initial value $y(0^+)$ for $Y(s) = 2s/(s^2+1)$:",
        choices: ["$2$", "$0$", "$1$", "$\\infty$"], correct: 0,
        solution: S({ c: "IVT: $\\lim_{s\\to\\infty} sY(s)$.", s: ["$\\lim 2s^2/(s^2+1) = 2$."], a: "$2$" }), ref: "p.56" },
      { q: "BIBO stability requires:",
        choices: ["Bounded input → bounded output", "Linear", "Time-invariant", "Causal"], correct: 0,
        solution: S({ c: "BIBO = Bounded-Input Bounded-Output.", s: ["For LTI: all poles in LHP."], a: "Bounded I/O" }), ref: "p.365" },
      { q: "Pole-zero cancellation may cause:",
        choices: ["Hidden modes (uncontrollable/unobservable)", "Always stable", "Infinite gain", "Phase shift"], correct: 0,
        solution: S({ c: "If unstable pole is canceled by zero, internal state may still grow → BIBO stable but internally unstable.", s: [""], a: "Hidden modes" }), ref: "p.365" },
    ],

    // Signal — +12
    8: [
      { q: "Nyquist rate for signal up to 20 kHz:",
        choices: ["$> 40$ kHz", "$20$ kHz", "$10$ kHz", "$80$ kHz"], correct: 0,
        solution: S({ c: "$f_s > 2 f_{max}$.", s: [""], a: "$> 40$ kHz" }), ref: "p.375" },
      { q: "Anti-aliasing filter type:",
        choices: ["Low-pass before sampler", "High-pass", "Notch", "Bandpass after"], correct: 0,
        solution: S({ c: "Anti-aliasing: remove frequencies above Nyquist before sampling.", s: [""], a: "LPF" }), ref: "p.375" },
      { q: "DFT bin spacing for $N$-point DFT, $f_s$ sampling:",
        choices: ["$f_s/N$ Hz", "$f_s$", "$2 f_s$", "$1$ Hz"], correct: 0,
        solution: S({ c: "Frequency resolution = $f_s/N$.", s: ["E.g., 1024-point at 8 kHz: bins every 7.8 Hz."], a: "$f_s/N$" }), ref: "p.376" },
      { q: "Hanning window vs rectangular: tradeoff:",
        choices: ["Hanning: less leakage but wider main lobe", "Same", "Hanning is faster", "Rect is better"], correct: 0,
        solution: S({ c: "Windowing reduces spectral leakage at cost of frequency resolution.", s: [""], a: "Less leakage, wider main lobe" }), ref: "p.376" },
      { q: "FIR filter: impulse response length 10. Group delay:",
        choices: ["$4.5$ samples (constant if symmetric)", "$10$", "$5$", "$0$"], correct: 0,
        solution: S({ c: "Linear-phase FIR (symmetric coefficients): group delay = $(N-1)/2$.", s: ["$N=10$: delay = 4.5 samples."], a: "$4.5$ samples" }), ref: "p.376" },
      { q: "Aliasing of 8 kHz signal sampled at 6 kHz:",
        choices: ["Apparent $2$ kHz ($|8-6|$)", "$8$ kHz", "$0$", "$14$ kHz"], correct: 0,
        solution: S({ c: "$8 > 3 = f_s/2$, alias to $|8-6| = 2$ kHz.", s: [""], a: "$2$ kHz" }), ref: "p.375" },
      { q: "Magnitude response of $H(j\\omega) = 1/(1 + j\\omega/\\omega_c)$ at $\\omega = \\omega_c$:",
        choices: ["$1/\\sqrt{2} = -3$ dB", "$1$", "$0$", "$1/2$"], correct: 0,
        solution: S({ c: "1st-order LPF at corner.", s: ["$|H| = 1/\\sqrt{1+1} = 1/\\sqrt{2}$. dB: $-3.01$."], a: "$-3$ dB" }), ref: "p.375" },
      { q: "$\\delta[n]$ Fourier transform (DTFT):",
        choices: ["Constant 1 (flat spectrum)", "$\\delta(\\omega)$", "$1/(j\\omega)$", "Cosine"], correct: 0,
        solution: S({ c: "Impulse has flat spectrum.", s: [""], a: "$1$" }), ref: "p.376" },
      { q: "Bode plot 1st-order pole at $\\omega = 10$. Asymptotic mag at $\\omega = 100$:",
        choices: ["$-20$ dB", "$0$ dB", "$-3$ dB", "$-40$ dB"], correct: 0,
        solution: S({ c: "1 decade above corner: -20 dB.", s: [""], a: "$-20$ dB" }), ref: "p.366" },
      { q: "Bode plot 1st-order zero at 10. Asymptotic mag at $\\omega = 100$:",
        choices: ["$+20$ dB", "$0$", "$-20$", "$+3$"], correct: 0,
        solution: S({ c: "Zero contributes +20 dB/decade above corner.", s: [""], a: "$+20$ dB" }), ref: "p.366" },
      { q: "Group delay of $H(s) = 1$ (unity):",
        choices: ["$0$", "$\\infty$", "$1$", "Undefined"], correct: 0,
        solution: S({ c: "Constant H = no delay or phase shift.", s: [""], a: "$0$" }), ref: "p.366" },
      { q: "Z-transform of $a^n u[n]$:",
        choices: ["$1/(1-az^{-1}) = z/(z-a)$", "$1$", "$z/(z+a)$", "$a^n/z$"], correct: 0,
        solution: S({ c: "Geometric Z-transform.", s: [""], a: "$z/(z-a)$" }), ref: "p.376" },
    ],

    // Electronics — +20
    9: [
      { q: "Inverting amp $R_f = 50$ k, $R_{in} = 5$ k, $v_{in} = 100$ mV. Output:",
        choices: ["$-1.0$ V", "$+1.0$ V", "$-10$ V", "$-0.01$ V"], correct: 0,
        solution: S({ c: "Gain $= -R_f/R_{in} = -10$.", s: ["$-10 \\cdot 0.1 = -1.0$ V."], a: "$-1.0$ V" }), ref: "p.380" },
      { q: "Non-inverting amp output when $v_{in} = 0$:",
        choices: ["$0$ V", "$\\infty$", "$V_{cc}$", "$-V_{cc}$"], correct: 0,
        solution: S({ c: "Linear with positive gain. $v_{out} = G \\cdot v_{in} = 0$.", s: [""], a: "$0$ V" }), ref: "p.380" },
      { q: "Voltage follower input impedance:",
        choices: ["Very high (ideal op-amp's $Z_{in}$)", "Zero", "$R$", "$1$ Ω"], correct: 0,
        solution: S({ c: "Buffer: no feedback to input → full op-amp Z_in seen.", s: [""], a: "Very high" }), ref: "p.380" },
      { q: "BJT bias: $V_{CC} = 12$, $R_C = 1$ kΩ, $R_B = 220$ kΩ, $\\beta = 100$. $V_{BE}=0.7$V. $I_B$:",
        choices: ["$\\approx 51.4$ µA", "$10$ mA", "$1$ mA", "$0.05$ mA"], correct: 0,
        solution: S({ c: "$I_B = (V_{CC} - V_{BE})/R_B$.", s: ["$(12-0.7)/220000 = 51.4$ µA."], a: "$\\approx 51.4$ µA" }), ref: "p.384" },
      { q: "Above BJT: $I_C$:",
        choices: ["$\\approx 5.14$ mA", "$0.5$ mA", "$50$ mA", "$1$ A"], correct: 0,
        solution: S({ c: "$I_C = \\beta I_B$.", s: ["$100 \\cdot 51.4 µA = 5.14$ mA."], a: "$\\approx 5.14$ mA" }), ref: "p.384" },
      { q: "$V_{CE}$ for above:",
        choices: ["$\\approx 6.86$ V (active region)", "$0.2$ V", "$12$ V", "$0$"], correct: 0,
        solution: S({ c: "$V_{CE} = V_{CC} - I_C R_C$.", s: ["$12 - 5.14 \\cdot 1 = 6.86$ V. Active region (between sat and cutoff)."], a: "$\\approx 6.86$ V" }), ref: "p.384" },
      { q: "Class A amp: transistor conducts for:",
        choices: ["Full 360°", "180°", "Pulses only", "Variable"], correct: 0,
        solution: S({ c: "Class A: continuous conduction → linear but inefficient.", s: [""], a: "$360°$" }), ref: "p.384" },
      { q: "Push-pull (Class B) amp uses:",
        choices: ["Two complementary transistors", "One BJT", "Single FET", "MOSFET only"], correct: 0,
        solution: S({ c: "Class B: NPN + PNP (or N/P MOSFET) — each conducts half-cycle.", s: ["Higher efficiency but crossover distortion."], a: "Complementary pair" }), ref: "p.384" },
      { q: "Zener regulator: $V_Z = 5.6$ V, $I_{Z,min} = 5$ mA. With load 1 kΩ, source 12V, find $R_s$:",
        choices: ["$\\approx 581$ Ω", "$1$ kΩ", "$100$ Ω", "$2$ kΩ"], correct: 0,
        solution: S({ c: "$R_s$ must allow $I_{load} + I_{Z,min}$ to flow.", s: ["$I_{load} = 5.6/1000 = 5.6$ mA.", "$I_s = I_{load} + I_Z = 5.6 + 5 = 10.6$ mA.", "$R_s = (12 - 5.6)/0.0106 = 604$ Ω. Close enough — round."], a: "$\\sim 600$ Ω" }), ref: "p.383" },
      { q: "Op-amp output current limit typically:",
        choices: ["~20-50 mA (general purpose)", "1 A", "1 µA", "Unlimited"], correct: 0,
        solution: S({ c: "Most general-purpose op-amps source/sink 20-50 mA short-circuit safe.", s: ["Power op-amps: 1-5 A."], a: "20-50 mA typical" }), ref: "p.380" },
      { q: "Common-emitter amplifier output impedance:",
        choices: ["$\\approx R_C$ (collector resistor)", "Very low", "Zero", "$r_e$"], correct: 0,
        solution: S({ c: "$Z_{out}$ at collector $\\approx R_C \\| r_o$, where $r_o$ usually large.", s: [""], a: "$R_C$" }), ref: "p.384" },
      { q: "Crystal oscillator stability:",
        choices: ["1-100 ppm typically", "1%", "10%", "No drift"], correct: 0,
        solution: S({ c: "Crystals: $10^{-6}$ to $10^{-8}$ stability over T.", s: ["TCXO (temp-compensated): even better. OCXO (oven-controlled): $10^{-9}$."], a: "1-100 ppm" }), ref: "p.380" },
      { q: "An LC oscillator frequency:",
        choices: ["$f_0 = 1/(2\\pi\\sqrt{LC})$", "$RC$", "Same as $\\omega L$", "Fixed"], correct: 0,
        solution: S({ c: "Tank circuit resonance.", s: [""], a: "$1/(2\\pi\\sqrt{LC})$" }), ref: "p.361" },
      { q: "Photodiode operating mode for max speed:",
        choices: ["Reverse bias", "Forward bias", "Zero bias", "AC"], correct: 0,
        solution: S({ c: "Reverse bias: widens depletion → faster carrier collection. Lower capacitance.", s: ["Zero bias (photovoltaic mode): low noise but slower."], a: "Reverse bias" }), ref: "p.383" },
      { q: "MOSFET enhancement vs depletion mode:",
        choices: ["Enhancement: needs gate V > $V_{th}$ to turn on; depletion conducts at $V_{GS}=0$", "Same", "Depletion is always on", "Enhancement is faster"], correct: 0,
        solution: S({ c: "Enhancement: 'normally off'. Depletion: 'normally on'.", s: [""], a: "Enhancement off, depletion on" }), ref: "p.386" },
      { q: "Power dissipated by 5V Zener carrying 100 mA:",
        choices: ["$0.5$ W", "$5$ W", "$50$ mW", "$2.5$ W"], correct: 0,
        solution: S({ c: "$P = V_Z \\cdot I_Z$.", s: ["$5 \\cdot 0.1 = 0.5$ W."], a: "$0.5$ W" }), ref: "p.383" },
      { q: "Inverting summer with $R_f = R_1 = R_2 = 10$ k. $v_1 = 1$, $v_2 = 2$. Output:",
        choices: ["$-3$ V", "$+3$ V", "$3/2$ V", "$0$"], correct: 0,
        solution: S({ c: "Summer: $v_{out} = -R_f \\sum v_i/R_i$.", s: ["All $R$ equal: $v_{out} = -(v_1 + v_2) = -3$."], a: "$-3$ V" }), ref: "p.380" },
      { q: "Common-source MOSFET amp output impedance:",
        choices: ["$R_D \\| r_o$", "Zero", "Infinite", "$r_e$"], correct: 0,
        solution: S({ c: "Parallel combination of drain resistor and intrinsic $r_o$.", s: [""], a: "$R_D \\| r_o$" }), ref: "p.386" },
      { q: "Buck-boost converter polarity of output (continuous mode):",
        choices: ["Opposite sign of input (inverted)", "Same sign", "Always positive", "AC"], correct: 0,
        solution: S({ c: "Standard buck-boost inverts polarity.", s: ["Non-inverting topologies (Ćuk, SEPIC) preserve polarity but more components."], a: "Inverted" }), ref: "p.383" },
      { q: "ADC SAR (Successive Approximation Register) speed:",
        choices: ["Medium ($\\sim$ MSps for 12-bit)", "Fastest", "Slow", "Hz range"], correct: 0,
        solution: S({ c: "SAR: binary search per bit. $N$-bit needs $N$ steps.", s: ["Pipelined: faster but more silicon.", "Sigma-delta: slow but high resolution.", "Flash: fastest but expensive."], a: "Medium speed" }), ref: "p.388" },
    ],

    // Power — +18
    10: [
      { q: "Line current for 30 kW load at $V_{LL} = 480$ V, $pf = 0.85$:",
        choices: ["$\\approx 42.5$ A", "$\\$30$ A", "$\\$60$ A", "$\\$15$ A"], correct: 0,
        solution: S({ c: "$P = \\sqrt{3} V_{LL} I_L \\cos\\theta$.", s: ["$I_L = P/(\\sqrt{3} V_{LL} \\cos\\theta) = 30000/(1.732 \\cdot 480 \\cdot 0.85) = 42.45$ A."], a: "$\\approx 42.5$ A" }), ref: "p.363" },
      { q: "Wye→Delta with each Y impedance $5\\angle 30°$ Ω. Delta phase Z:",
        choices: ["$15\\angle 30°$ Ω", "$5\\angle 30°$", "$1.67\\angle 30°$", "$25\\angle 60°$"], correct: 0,
        solution: S({ c: "Balanced Y→Δ: $Z_\\Delta = 3 Z_Y$.", s: ["$3 \\cdot 5\\angle 30° = 15\\angle 30°$."], a: "$15\\angle 30°$" }), ref: "p.363" },
      { q: "Transformer with primary 240V, secondary 24V. Reflect 10Ω load on secondary to primary:",
        choices: ["$1000$ Ω", "$1$ Ω", "$10$ Ω", "$100$ Ω"], correct: 0,
        solution: S({ c: "$Z' = a^2 Z$. $a = 10$.", s: ["$10^2 \\cdot 10 = 1000$ Ω."], a: "$1000$ Ω" }), ref: "p.364" },
      { q: "Motor at 60 Hz, 4 poles, 1750 rpm full-load. Slip:",
        choices: ["$\\approx 2.8\\%$", "$5\\%$", "$10\\%$", "$0$"], correct: 0,
        solution: S({ c: "Sync: $n_s = 120f/p = 1800$. Slip: $(1800-1750)/1800$.", s: ["$50/1800 = 2.78\\%$."], a: "$\\approx 2.78\\%$" }), ref: "p.365" },
      { q: "DC motor armature current with $V = 220$V, $E_b = 200$V, $R_a = 0.5$Ω:",
        choices: ["$40$ A", "$20$ A", "$440$ A", "$100$ A"], correct: 0,
        solution: S({ c: "$I_a = (V - E_b)/R_a$.", s: ["$(220-200)/0.5 = 40$ A."], a: "$40$ A" }), ref: "p.365" },
      { q: "Active power formula in three-phase using line quantities:",
        choices: ["$P = \\sqrt{3} V_{LL} I_L \\cos\\theta$", "$P = V_{LL} I_L \\cos\\theta$", "$P = 3 V_{LL} I_L$", "$V/R$"], correct: 0,
        solution: S({ c: "Standard 3-φ formula (Y or Δ).", s: [""], a: "$\\sqrt{3} V_{LL} I_L \\cos\\theta$" }), ref: "p.363" },
      { q: "Transformer turns ratio 10:1 step down. Apply 4800V primary, get:",
        choices: ["$480$ V", "$48{,}000$ V", "$4800$ V", "$48$ V"], correct: 0,
        solution: S({ c: "$V_2 = V_1/a$.", s: ["$4800/10 = 480$ V."], a: "$480$ V" }), ref: "p.364" },
      { q: "Apparent vs real power: $|S|^2$ =",
        choices: ["$P^2 + Q^2$", "$P + Q$", "$P - Q$", "$P/Q$"], correct: 0,
        solution: S({ c: "Power triangle: $|S|^2 = P^2 + Q^2$.", s: [""], a: "$P^2+Q^2$" }), ref: "p.362" },
      { q: "Per-unit impedance of 50 MVA, 13.8 kV transformer with $Z_{actual} = 0.5$ Ω:",
        choices: ["$\\approx 0.131$ pu", "$0.5$ pu", "$1.0$ pu", "$10$ pu"], correct: 0,
        solution: S({ c: "$Z_{base} = V^2/S$. $Z_{pu} = Z_{actual}/Z_{base}$.", s: ["$Z_{base} = 13800^2/50000000 = 3.808$ Ω.", "$Z_{pu} = 0.5/3.808 = 0.131$ pu."], a: "$0.131$ pu" }), ref: "p.363" },
      { q: "Synchronous speed of 2-pole machine at 50 Hz:",
        choices: ["$3000$ rpm", "$1500$ rpm", "$6000$ rpm", "$1800$ rpm"], correct: 0,
        solution: S({ c: "$n_s = 120 f / p$.", s: ["$120 \\cdot 50/2 = 3000$ rpm."], a: "$3000$ rpm" }), ref: "p.365" },
      { q: "Three-phase rectifier output ripple vs single-phase:",
        choices: ["Lower ripple, 6-pulse per cycle", "Higher", "Same", "Zero"], correct: 0,
        solution: S({ c: "3-φ full-wave: 6 pulses/cycle → smoother DC.", s: ["1-φ full-wave: 2 pulses."], a: "Lower ripple" }), ref: "p.383" },
      { q: "Power factor 0.5 lagging means:",
        choices: ["$\\theta = 60°$, current lags voltage", "Resistive", "Capacitive", "Leading"], correct: 0,
        solution: S({ c: "$\\cos 60° = 0.5$. Lagging → inductive.", s: [""], a: "$60°$ lag (inductive)" }), ref: "p.362" },
      { q: "Voltage drop in transmission line approximately:",
        choices: ["$V_R \\approx |I|(R\\cos\\theta + X\\sin\\theta)$", "$IR$ only", "$IZ$ vector", "$V$"], correct: 0,
        solution: S({ c: "Approximate voltage regulation: $\\Delta V = I(R\\cos\\theta + X\\sin\\theta)$.", s: ["Sometimes called Vd formula in distribution analysis."], a: "$IR\\cos+IX\\sin$" }), ref: "p.363" },
      { q: "Why X >> R for long transmission lines:",
        choices: ["Inductive reactance dominates over copper R", "Capacitive", "Mutual coupling", "Frequency low"], correct: 0,
        solution: S({ c: "Long lines: inductance per km × length grows; R relatively small.", s: ["Why power flow controlled mostly by phase angle (governed by reactance)."], a: "$X$ dominant" }), ref: "p.363" },
      { q: "Capacitor bank for PF correction: $P = 50$ kW, raise PF 0.7→0.95:",
        choices: ["$\\approx 34.6$ kVAR", "$50$ kVAR", "$10$ kVAR", "$15$ kVAR"], correct: 0,
        solution: S({ c: "$Q_C = P(\\tan\\theta_1 - \\tan\\theta_2)$.", s: ["$\\theta_1 = \\arccos 0.7 = 45.57°$, $\\tan = 1.0202$.", "$\\theta_2 = \\arccos 0.95 = 18.19°$, $\\tan = 0.3287$.", "$Q_C = 50(1.0202 - 0.3287) = 50 \\cdot 0.6915 = 34.58$ kVAR."], a: "$\\approx 34.6$ kVAR" }), ref: "p.362" },
      { q: "Three-phase fault current $I_{SC}$ in pu: $V_{pu} = 1.0$, $Z_{pu} = 0.1$:",
        choices: ["$10$ pu", "$1$ pu", "$0.1$ pu", "$100$ pu"], correct: 0,
        solution: S({ c: "$I_{SC,pu} = V_{pu}/Z_{pu}$.", s: ["$1/0.1 = 10$ pu."], a: "$10$ pu" }), ref: "p.363" },
      { q: "DC generator with $V_t = 240$V, $I_a = 50$A, $R_a = 0.2$Ω. Generated EMF:",
        choices: ["$250$ V", "$240$ V", "$230$ V", "$10$ V"], correct: 0,
        solution: S({ c: "Generator: $E_g = V_t + I_a R_a$ (drop is across armature when delivering current).", s: ["$240 + 50 \\cdot 0.2 = 250$ V."], a: "$250$ V" }), ref: "p.365" },
      { q: "Service factor of motor at FL means:",
        choices: ["Continuous-duty capacity multiplier of nameplate rating", "Voltage tolerance", "Frequency", "Starting current"], correct: 0,
        solution: S({ c: "SF: how much above nameplate the motor can run continuously without damage.", s: ["SF 1.0: only at nameplate.", "SF 1.15-1.25: typical general-purpose."], a: "Continuous overload" }), ref: "p.365" },
    ],

    // EM — +8
    11: [
      { q: "EM wave wavelength in vacuum at 300 MHz:",
        choices: ["$1$ m", "$300$ m", "$0.3$ m", "$3$ m"], correct: 0,
        solution: S({ c: "$\\lambda = c/f$.", s: ["$3 \\cdot 10^8 / 3 \\cdot 10^8 = 1$ m."], a: "$1$ m" }), ref: "p.368" },
      { q: "Power density of EM wave with $E_{rms} = 1$ V/m in vacuum:",
        choices: ["$\\approx 2.65$ mW/m²", "$1$ W/m²", "$120\\pi$ W/m²", "$0$"], correct: 0,
        solution: S({ c: "Poynting vector magnitude: $S = E^2/\\eta_0$. $\\eta_0 \\approx 377$ Ω.", s: ["$1^2/377 \\approx 2.65$ mW/m²."], a: "$\\approx 2.65$ mW/m²" }), ref: "p.368" },
      { q: "$\\nabla \\cdot \\vec{E} = \\rho/\\varepsilon_0$ is:",
        choices: ["Gauss's law (E-field divergence from charge)", "Faraday", "Ampere", "Coulomb"], correct: 0,
        solution: S({ c: "First Maxwell equation.", s: [""], a: "Gauss" }), ref: "p.355" },
      { q: "Permittivity of vacuum $\\varepsilon_0$ ≈",
        choices: ["$8.854 \\times 10^{-12}$ F/m", "$1$ F/m", "$\\mu_0$", "$10^{-7}$"], correct: 0,
        solution: S({ c: "Memorized constant.", s: [""], a: "$8.854\\times 10^{-12}$ F/m" }), ref: "p.355" },
      { q: "Transmission line characteristic impedance for $L'=0.5$ µH/m, $C'=200$ pF/m:",
        choices: ["$50$ Ω", "$100$ Ω", "$25$ Ω", "$0.5$ Ω"], correct: 0,
        solution: S({ c: "$Z_0 = \\sqrt{L/C}$.", s: ["$\\sqrt{0.5e-6/200e-12} = \\sqrt{2500} = 50$ Ω."], a: "$50$ Ω" }), ref: "p.368" },
      { q: "Reflection coefficient at matched load:",
        choices: ["$\\Gamma = 0$ (no reflection)", "$1$", "$-1$", "Infinite"], correct: 0,
        solution: S({ c: "$Z_L = Z_0$ → $\\Gamma = 0$. All power absorbed.", s: [""], a: "$0$" }), ref: "p.368" },
      { q: "Short-circuited transmission line: $\\Gamma$ at short:",
        choices: ["$-1$ (180° phase flip)", "$+1$", "$0$", "$0.5$"], correct: 0,
        solution: S({ c: "Short ($Z_L=0$): $\\Gamma = (0-Z_0)/(0+Z_0) = -1$.", s: ["Open: $\\Gamma = +1$."], a: "$-1$" }), ref: "p.368" },
      { q: "Microstrip $Z_0$ depends on:",
        choices: ["Trace width, dielectric height, $\\varepsilon_r$", "Just length", "Frequency only", "Color"], correct: 0,
        solution: S({ c: "Microstrip impedance formulas: depend on geometry and substrate.", s: ["Standard: 50 Ω with W/H ratio depending on dielectric."], a: "Geometry + $\\varepsilon_r$" }), ref: "p.368" },
    ],

    // Control — +12
    12: [
      { q: "PID controller transfer function in parallel form:",
        choices: ["$K_p + K_i/s + K_d s$", "$K_p(K_i)(K_d)$", "$K/s$", "Just $K$"], correct: 0,
        solution: S({ c: "Standard PID.", s: [""], a: "$K_p+K_i/s+K_d s$" }), ref: "p.366" },
      { q: "Pure proportional control of plant $G = 1/(s+1)$, K = 10. Closed-loop pole:",
        choices: ["$s = -11$", "$s = -1$", "$s = -10$", "$s = -1/10$"], correct: 0,
        solution: S({ c: "$T = KG/(1+KG) = 10/(s+1+10) = 10/(s+11)$.", s: [""], a: "$s = -11$" }), ref: "p.365" },
      { q: "If $G(s) = K/s$ and $H(s) = 1$ (unity feedback), closed-loop is:",
        choices: ["$K/(s+K)$ (1st-order LPF)", "$1$", "$1/(s+1)$", "$Ks$"], correct: 0,
        solution: S({ c: "$T = G/(1+G) = (K/s)/(1+K/s) = K/(s+K)$.", s: ["Pole at $-K$. DC gain = 1."], a: "$K/(s+K)$" }), ref: "p.365" },
      { q: "Gain crossover frequency $\\omega_{gc}$:",
        choices: ["Where $|G(j\\omega)H(j\\omega)| = 1$", "Where phase = 0", "DC", "Resonance"], correct: 0,
        solution: S({ c: "$\\omega_{gc}$: magnitude crosses 1 (0 dB).", s: ["Used to find phase margin."], a: "$|GH| = 1$" }), ref: "p.366" },
      { q: "Phase crossover frequency $\\omega_{pc}$:",
        choices: ["Where phase = -180°", "Where gain = 1", "DC", "Resonance"], correct: 0,
        solution: S({ c: "$\\omega_{pc}$: phase crosses -180°.", s: ["Used to find gain margin."], a: "Phase = $-180°$" }), ref: "p.366" },
      { q: "Lead compensator effect on $\\omega_{gc}$:",
        choices: ["Shifts $\\omega_{gc}$ higher (faster response)", "Shifts lower", "No effect", "Random"], correct: 0,
        solution: S({ c: "Lead adds gain at high freq → pushes crossover higher.", s: ["Result: faster transient response."], a: "Higher $\\omega_{gc}$" }), ref: "p.366" },
      { q: "Acceptable gain margin minimum:",
        choices: ["$\\ge 6$ dB typically", "$0$ dB", "$\\infty$", "$3$ dB"], correct: 0,
        solution: S({ c: "Design rule of thumb: GM ≥ 6 dB.", s: ["Combined with PM ≥ 30° for robust design."], a: "$\\ge 6$ dB" }), ref: "p.366" },
      { q: "Acceptable phase margin minimum:",
        choices: ["$\\ge 30°$ (60° is better)", "$\\ge 0°$", "$\\ge 90°$", "$0°$"], correct: 0,
        solution: S({ c: "PM ≥ 30° minimum, 45-60° typical target.", s: [""], a: "$\\ge 30°$" }), ref: "p.366" },
      { q: "Integral term in PI controller eliminates:",
        choices: ["Steady-state error to step", "Overshoot", "Noise", "Settling time"], correct: 0,
        solution: S({ c: "Integral adds a pole at origin → raises system type → zeros SS error to step.", s: [""], a: "SS step error" }), ref: "p.366" },
      { q: "Derivative term in PID:",
        choices: ["Improves damping but amplifies noise", "No effect", "Eliminates offset", "Adds gain only"], correct: 0,
        solution: S({ c: "D term: phase lead → damping. But high-freq noise amplified.", s: ["Usually filtered: D acts on filtered signal."], a: "Damping + noise issue" }), ref: "p.366" },
      { q: "Time scaling: if $G(s)$ stable, $G(s/T)$ for $T > 0$:",
        choices: ["Still stable but slower", "Unstable", "Faster", "Unrelated"], correct: 0,
        solution: S({ c: "$s \\to s/T$ scales time. Poles scale by T. All move along ray from origin.", s: ["LHP stays LHP for $T>0$."], a: "Stable, slower" }), ref: "p.365" },
      { q: "Closed-loop bandwidth ≈ gain crossover frequency for:",
        choices: ["Common 1st-order or moderately damped systems", "Always", "Never", "Only DC"], correct: 0,
        solution: S({ c: "Rule of thumb for moderate $\\zeta$. Exact relationship depends on system.", s: [""], a: "Approximately equal" }), ref: "p.366" },
    ],

    // Comm — +12
    13: [
      { q: "BPSK transmits how many bits per symbol?",
        choices: ["$1$", "$2$", "$4$", "$8$"], correct: 0,
        solution: S({ c: "BPSK: 2 phase states → 1 bit.", s: [""], a: "$1$" }), ref: "p.371" },
      { q: "QPSK uses ___ symbol states:",
        choices: ["$4$ (2 bits each)", "$2$", "$8$", "$16$"], correct: 0,
        solution: S({ c: "Quadrature PSK: 4 phases.", s: [""], a: "$4$" }), ref: "p.371" },
      { q: "16-QAM transmits ___ bits per symbol:",
        choices: ["$4$", "$2$", "$8$", "$16$"], correct: 0,
        solution: S({ c: "$\\log_2 16 = 4$ bits.", s: [""], a: "$4$" }), ref: "p.371" },
      { q: "AM bandwidth for message with $f_m$ = 5 kHz:",
        choices: ["$10$ kHz", "$5$ kHz", "$2.5$ kHz", "$15$ kHz"], correct: 0,
        solution: S({ c: "AM: $BW = 2 f_m$.", s: [""], a: "$10$ kHz" }), ref: "p.371" },
      { q: "SSB bandwidth for message with $f_m$ = 5 kHz:",
        choices: ["$5$ kHz", "$10$ kHz", "$2.5$ kHz", "$15$ kHz"], correct: 0,
        solution: S({ c: "SSB: only $f_m$. Half of AM.", s: [""], a: "$5$ kHz" }), ref: "p.371" },
      { q: "Carrier-to-noise ratio (CNR) units:",
        choices: ["dB (logarithmic ratio)", "Watts", "Hz", "Volts"], correct: 0,
        solution: S({ c: "Ratio in dB.", s: [""], a: "dB" }), ref: "p.371" },
      { q: "Spectral efficiency unit:",
        choices: ["bps/Hz", "bps", "Hz/bit", "W/Hz"], correct: 0,
        solution: S({ c: "Bits per second per Hz of bandwidth.", s: [""], a: "bps/Hz" }), ref: "p.371" },
      { q: "Shannon limit for AWGN channel:",
        choices: ["$C = B\\log_2(1 + S/N)$ bps", "$C = BS/N$", "$C = SN/B$", "$C = SNR$"], correct: 0,
        solution: S({ c: "Shannon-Hartley theorem.", s: [""], a: "$B\\log_2(1+S/N)$" }), ref: "p.371" },
      { q: "Carrier frequency 100 MHz, FM deviation 50 kHz, audio 10 kHz. Carson BW:",
        choices: ["$120$ kHz", "$50$ kHz", "$200$ kHz", "$100$ MHz"], correct: 0,
        solution: S({ c: "Carson: $BW = 2(\\Delta f + f_m)$.", s: ["$2(50 + 10) = 120$ kHz."], a: "$120$ kHz" }), ref: "p.371" },
      { q: "Source coding (compression):",
        choices: ["Removes redundancy in data", "Adds error correction", "Modulates", "Encrypts"], correct: 0,
        solution: S({ c: "Source coding: minimize bits to represent info (e.g., Huffman, LZ).", s: ["Channel coding: add redundancy for error correction."], a: "Compression" }), ref: "p.371" },
      { q: "Channel coding rate $R_c = k/n$ means:",
        choices: ["k info bits per n coded bits", "k errors per n bits", "Speed", "Frequency"], correct: 0,
        solution: S({ c: "Code rate: info / total. Lower rate = more redundancy.", s: ["E.g., (7,4) Hamming: rate 4/7."], a: "$k$ info per $n$ coded" }), ref: "p.371" },
      { q: "Differential encoding (e.g., DPSK):",
        choices: ["Encodes by phase changes (not absolute phase)", "Differential equation", "Subtracts", "Linear"], correct: 0,
        solution: S({ c: "DPSK: receiver doesn't need phase reference. Compares current vs previous symbol.", s: ["Cost: 3 dB worse BER vs coherent.", "Benefit: no phase recovery needed."], a: "Phase changes" }), ref: "p.371" },
    ],

    // Networks — +10
    14: [
      { q: "MAC address bytes:",
        choices: ["$6$ (48 bits)", "$4$", "$8$", "$32$"], correct: 0,
        solution: S({ c: "Standard MAC: 48 bits = 6 bytes.", s: ["Format: XX:XX:XX:XX:XX:XX (hex)."], a: "$6$ bytes" }), ref: "p.399" },
      { q: "IPv4 multicast address range:",
        choices: ["$224.0.0.0 - 239.255.255.255$ (Class D)", "$10.0.0.0/8$", "$127.0.0.0/8$", "$192.168.0.0/16$"], correct: 0,
        solution: S({ c: "Class D: 224.0.0.0/4. Multicast group addressing.", s: ["Used in: streaming, IGMP, OSPF, video conferencing."], a: "$224-239$" }), ref: "p.394" },
      { q: "Hub vs switch differences:",
        choices: ["Hub broadcasts to all ports; switch forwards selectively by MAC", "Same", "Hub is newer", "Switch slower"], correct: 0,
        solution: S({ c: "Hub: physical layer repeater. Switch: data link, learns MAC table.", s: [""], a: "Hub broadcast, switch forward" }), ref: "p.399" },
      { q: "OSPF uses what algorithm to find shortest path?",
        choices: ["Dijkstra's", "Bellman-Ford", "Floyd-Warshall", "Heap sort"], correct: 0,
        solution: S({ c: "OSPF: link-state protocol using Dijkstra's algorithm.", s: ["RIP uses Bellman-Ford (distance-vector)."], a: "Dijkstra" }), ref: "p.400" },
      { q: "Default gateway:",
        choices: ["Router for traffic outside local subnet", "DNS server", "Switch", "DHCP server"], correct: 0,
        solution: S({ c: "Default gateway: where to send packets destined outside the host's subnet.", s: ["Typically configured via DHCP."], a: "Outbound router" }), ref: "p.400" },
      { q: "Latency in ms = round-trip time. For 10 ms RTT, propagation delay (assuming negligible queuing):",
        choices: ["$\\approx 5$ ms one-way", "$10$ ms one-way", "$0$", "$100$ ms"], correct: 0,
        solution: S({ c: "RTT = 2× one-way.", s: ["One-way ≈ 5 ms."], a: "$\\approx 5$ ms" }), ref: "p.399" },
      { q: "VLAN purpose:",
        choices: ["Logical segmentation on physical switch", "Encryption", "Speed boost", "Routing"], correct: 0,
        solution: S({ c: "VLAN: isolated broadcast domains on shared switch.", s: ["Used: separating departments, security zones, IP phones."], a: "Logical segmentation" }), ref: "p.399" },
      { q: "Reliable delivery in TCP enforced by:",
        choices: ["Sequence numbers + ACKs + retransmission", "Just sequence numbers", "Just ACK", "UDP fallback"], correct: 0,
        solution: S({ c: "TCP: sender numbers bytes; receiver ACKs. Lost or unACKed → resend.", s: [""], a: "Seq + ACK + retx" }), ref: "p.400" },
      { q: "UDP characteristics:",
        choices: ["Connectionless, no reliability, low overhead", "Connection-oriented", "Reliable", "Heavy header"], correct: 0,
        solution: S({ c: "UDP: 8-byte header, fire-and-forget.", s: ["Used: DNS queries, video streaming, gaming, VoIP."], a: "Connectionless, fast" }), ref: "p.400" },
      { q: "ARP request is sent to:",
        choices: ["Broadcast MAC FF:FF:FF:FF:FF:FF", "Specific MAC", "Multicast", "Source"], correct: 0,
        solution: S({ c: "ARP request: 'who has this IP?' — broadcast on local network.", s: ["Reply: unicast back to requester."], a: "Broadcast" }), ref: "p.399" },
    ],

    // Digital — +20
    15: [
      { q: "Binary 10101010 in decimal:",
        choices: ["$170$", "$85$", "$255$", "$160$"], correct: 0,
        solution: S({ c: "$128+32+8+2 = 170$.", s: [""], a: "$170$" }), ref: "p.388" },
      { q: "Hex 0xFF in decimal:",
        choices: ["$255$", "$256$", "$15$", "$170$"], correct: 0,
        solution: S({ c: "$F = 15$. $15 \\cdot 16 + 15 = 255$.", s: [""], a: "$255$" }), ref: "p.388" },
      { q: "Largest 16-bit unsigned integer:",
        choices: ["$65{,}535$", "$32{,}767$", "$255$", "$65{,}536$"], correct: 0,
        solution: S({ c: "$2^{16} - 1$.", s: [""], a: "$65535$" }), ref: "p.389" },
      { q: "Two's complement 8-bit range:",
        choices: ["$-128$ to $+127$", "$-127$ to $+128$", "$0$ to $255$", "$-255$ to $+255$"], correct: 0,
        solution: S({ c: "Signed n-bit: $-2^{n-1}$ to $2^{n-1}-1$.", s: [""], a: "$-128$ to $+127$" }), ref: "p.389" },
      { q: "Boolean: $A + AB$ simplifies to:",
        choices: ["$A$ (absorption)", "$AB$", "$B$", "$0$"], correct: 0,
        solution: S({ c: "Absorption: $A + AB = A(1+B) = A$.", s: [""], a: "$A$" }), ref: "p.389" },
      { q: "Boolean: $AB + A\\bar{B}$:",
        choices: ["$A$", "$B$", "$AB$", "$\\bar{B}$"], correct: 0,
        solution: S({ c: "Factor: $A(B + \\bar{B}) = A \\cdot 1 = A$.", s: [""], a: "$A$" }), ref: "p.389" },
      { q: "NOR truth: 1 iff:",
        choices: ["Both inputs are 0", "Both 1", "Differ", "Same"], correct: 0,
        solution: S({ c: "NOR = NOT OR. True only when all inputs 0.", s: [""], a: "Both 0" }), ref: "p.389" },
      { q: "NAND truth: 0 iff:",
        choices: ["Both 1", "Both 0", "Differ", "Same"], correct: 0,
        solution: S({ c: "NAND = NOT AND. False only when all inputs 1.", s: [""], a: "Both 1" }), ref: "p.389" },
      { q: "Half adder Sum (XOR) and Carry (AND): inputs $A=B=1$:",
        choices: ["Sum=0, Carry=1", "S=1, C=1", "S=1, C=0", "S=0, C=0"], correct: 0,
        solution: S({ c: "$1 \\oplus 1 = 0$. $1 \\cdot 1 = 1$.", s: [""], a: "S=0, C=1" }), ref: "p.390" },
      { q: "Mod-10 counter (decade): how many flip-flops minimum?",
        choices: ["$4$ (need 10 states ≤ $2^4$)", "$10$", "$3$", "$5$"], correct: 0,
        solution: S({ c: "$\\lceil\\log_2 10\\rceil = 4$.", s: ["4 FFs handle 0-15; logic resets at 10 → 0."], a: "$4$" }), ref: "p.391" },
      { q: "Mealy machine outputs change when:",
        choices: ["State or input changes", "Clock edge only", "Power-on", "Reset"], correct: 0,
        solution: S({ c: "Mealy: combinational output = $f(\\text{state, input})$. Changes with either.", s: [""], a: "State or input" }), ref: "p.391" },
      { q: "D-FF setup violation cause:",
        choices: ["Metastability — output may be neither 0 nor 1 temporarily", "Faster operation", "Damage", "Reset"], correct: 0,
        solution: S({ c: "Setup violation: input changing too close to clock edge → unpredictable state.", s: ["Resolved with synchronizers (two-FF chain) when crossing clock domains."], a: "Metastability" }), ref: "p.391" },
      { q: "BCD: 7 in 4 bits:",
        choices: ["$0111$", "$111$", "$1000$", "$0110$"], correct: 0,
        solution: S({ c: "7 = 4+2+1 = 0111.", s: [""], a: "$0111$" }), ref: "p.388" },
      { q: "Bitwise XOR of $1100$ and $1010$:",
        choices: ["$0110$", "$1000$", "$1110$", "$0000$"], correct: 0,
        solution: S({ c: "XOR: 1 when differ.", s: ["1100", "1010", "0110."], a: "$0110$" }), ref: "p.388" },
      { q: "PLA (Programmable Logic Array) vs PAL:",
        choices: ["PLA: programmable AND + OR; PAL: prog AND + fixed OR", "Same", "PAL is older only", "PLA has fewer outputs"], correct: 0,
        solution: S({ c: "PLA more flexible; PAL simpler.", s: ["Both predecessors to modern FPGAs/CPLDs."], a: "PLA: both prog; PAL: fixed OR" }), ref: "p.390" },
      { q: "Tristate buffer outputs when enable is low (active-high enable):",
        choices: ["High impedance (Hi-Z)", "$0$", "$1$", "Floating undefined"], correct: 0,
        solution: S({ c: "Disabled tristate: output disconnected from line.", s: ["Allows shared bus with multiple drivers."], a: "Hi-Z" }), ref: "p.391" },
      { q: "Don't care in K-map represented by:",
        choices: ["$X$ or $d$", "$0$", "$1$", "Empty"], correct: 0,
        solution: S({ c: "Don't cares: cells where output value doesn't matter. Use to simplify.", s: [""], a: "$X$ / $d$" }), ref: "p.390" },
      { q: "Convert decimal 25 to binary:",
        choices: ["$11001$", "$10101$", "$01001$", "$10011$"], correct: 0,
        solution: S({ c: "$25 = 16+8+1 = 11001$.", s: [""], a: "$11001$" }), ref: "p.388" },
      { q: "Hex 0x1A + 0x06 = ?",
        choices: ["$0x20$", "$0x1F$", "$0x26$", "$0x16$"], correct: 0,
        solution: S({ c: "26 + 6 = 32 = 0x20.", s: [""], a: "$0x20$" }), ref: "p.388" },
      { q: "How many bits to address 1 MB byte-addressable memory:",
        choices: ["$20$", "$10$", "$30$", "$24$"], correct: 0,
        solution: S({ c: "$2^{20} = 1048576 \\approx 1$ MB.", s: [""], a: "$20$" }), ref: "p.407" },
    ],

    // CompSys — +10
    16: [
      { q: "Pipeline IF, ID, EX, MEM, WB stages: standard for:",
        choices: ["Classic RISC 5-stage", "x86", "ARM7", "GPU"], correct: 0,
        solution: S({ c: "MIPS classic 5-stage pipeline. Used in textbooks for clarity.", s: [""], a: "RISC 5-stage" }), ref: "p.408" },
      { q: "Cache locality types:",
        choices: ["Temporal + Spatial", "Time + Space + Code", "Just spatial", "Memory + I/O"], correct: 0,
        solution: S({ c: "Temporal: recent access likely repeated. Spatial: nearby data accessed together.", s: [""], a: "Temporal + Spatial" }), ref: "p.407" },
      { q: "Direct-mapped cache: address with 4-bit offset, 6-bit index, 22-bit tag. Cache size:",
        choices: ["$2^{6} \\cdot 2^4 = 1024$ bytes = 1 KB", "$2^{22}$", "$64$ bytes", "$10$ KB"], correct: 0,
        solution: S({ c: "Lines = $2^6 = 64$. Line size = $2^4 = 16$ bytes. Total $= 1024$.", s: [""], a: "$1$ KB" }), ref: "p.407" },
      { q: "Volatility: which RAM is volatile?",
        choices: ["DRAM and SRAM (both)", "Only DRAM", "Only SRAM", "Neither"], correct: 0,
        solution: S({ c: "Both lose contents without power. Flash/ROM is non-volatile.", s: [""], a: "Both" }), ref: "p.407" },
      { q: "Word-aligned data for 32-bit machine:",
        choices: ["Address divisible by 4", "By 8", "By 1", "Random"], correct: 0,
        solution: S({ c: "4-byte words: align at 4-byte boundaries.", s: ["64-bit: align at 8."], a: "Divisible by 4" }), ref: "p.407" },
      { q: "Floating-point IEEE 754 single-precision:",
        choices: ["1 sign + 8 exponent + 23 mantissa = 32 bits", "16 bits", "64 bits", "Variable"], correct: 0,
        solution: S({ c: "Standard single-precision: 1+8+23.", s: ["Double: 1+11+52."], a: "1+8+23" }), ref: "p.388" },
      { q: "Cache coherence protocols (multicore): MESI states:",
        choices: ["Modified, Exclusive, Shared, Invalid", "Memory ECC", "Sync, write", "Stack"], correct: 0,
        solution: S({ c: "MESI cache line states.", s: [""], a: "MESI" }), ref: "p.408" },
      { q: "Process address space components:",
        choices: ["Text, data, heap, stack", "Just code", "Just data", "Memory"], correct: 0,
        solution: S({ c: "Typical process layout: code (text), initialized data, BSS, heap (grows up), stack (grows down).", s: [""], a: "Text/data/heap/stack" }), ref: "p.408" },
      { q: "Interrupt vs trap:",
        choices: ["Interrupt: external; trap: software-triggered", "Same", "Trap is faster", "Interrupt is for OS only"], correct: 0,
        solution: S({ c: "Interrupt: async hardware event. Trap: synchronous software event (syscall, div-by-zero).", s: [""], a: "External vs internal" }), ref: "p.408" },
      { q: "Hyperthreading:",
        choices: ["One physical core appears as 2 logical (better utilization)", "Two cores in one", "Faster clock", "Encryption"], correct: 0,
        solution: S({ c: "Intel HT: share execution resources between threads. Up to ~30% throughput gain.", s: [""], a: "Logical core sharing" }), ref: "p.408" },
    ],

    // Software — +10
    17: [
      { q: "Algorithm complexity of Heapsort:",
        choices: ["$O(n\\log n)$ worst case", "$O(n^2)$", "$O(n)$", "$O(\\log n)$"], correct: 0,
        solution: S({ c: "Heapsort: build heap O(n), then n extracts at O(log n) each.", s: ["Total $O(n\\log n)$ guaranteed (unlike quicksort which can be $O(n^2)$)."], a: "$O(n\\log n)$" }), ref: "p.415" },
      { q: "Hash collision resolution: chaining means:",
        choices: ["Linked list at each bucket", "Probe next bucket", "Discard", "Resize immediately"], correct: 0,
        solution: S({ c: "Chaining: multiple items in same bucket linked.", s: ["Open addressing: probe sequence.", "Both maintain $O(1)$ avg if load low."], a: "Linked list per bucket" }), ref: "p.415" },
      { q: "Tail recursion can be optimized to:",
        choices: ["Iteration (no stack growth)", "Faster recursion", "Same as regular", "Faster memory"], correct: 0,
        solution: S({ c: "Tail call: last action is recursive call. Compiler can reuse current stack frame.", s: ["Avoids stack overflow for deep recursion.", "Some languages (Scheme, Scala) guarantee TCO."], a: "Iteration (TCO)" }), ref: "p.415" },
      { q: "Compile-time vs run-time:",
        choices: ["Compile: before exec; run-time: during exec", "Same", "Compile is faster", "Random"], correct: 0,
        solution: S({ c: "Compile-time: code generation, static checks. Run-time: actual execution.", s: ["Templates/macros: compile-time. Reflection: run-time."], a: "Before vs during exec" }), ref: "p.415" },
      { q: "Linked list vs array dynamic insertion:",
        choices: ["List: $O(1)$ with pointer; Array: $O(n)$ shift", "Both $O(1)$", "Both $O(n)$", "List slower"], correct: 0,
        solution: S({ c: "List relink pointers. Array shift remaining elements.", s: [""], a: "List faster (with pointer)" }), ref: "p.415" },
      { q: "Bubble sort best case:",
        choices: ["$O(n)$ if optimized with early exit on sorted input", "Always $O(n^2)$", "$O(\\log n)$", "$O(n!)$"], correct: 0,
        solution: S({ c: "Optimized bubble: detect no swaps in a pass → already sorted, exit.", s: [""], a: "$O(n)$ best (sorted)" }), ref: "p.415" },
      { q: "Recursive vs iterative tree traversal:",
        choices: ["Recursive cleaner; iterative may need explicit stack", "Recursive slower", "Same code", "Iterative is impossible"], correct: 0,
        solution: S({ c: "Tree traversal naturally recursive; iterative needs stack to simulate call frames.", s: [""], a: "Recursive cleaner" }), ref: "p.415" },
      { q: "Garbage collection (GC) in Java/C#/Python:",
        choices: ["Automatic memory management", "Manual free", "Stack only", "No effect"], correct: 0,
        solution: S({ c: "GC: runtime reclaims unreferenced memory.", s: ["Generational GC: optimize for short-lived objects.", "Tradeoff: pauses, overhead."], a: "Auto mem management" }), ref: "p.415" },
      { q: "Trie data structure:",
        choices: ["Tree for storing strings with shared prefixes", "Hash variant", "Array", "Stack"], correct: 0,
        solution: S({ c: "Trie: each node represents a character. Path from root spells a string.", s: ["Used: autocomplete, dictionary, IP routing tables."], a: "Prefix tree" }), ref: "p.415" },
      { q: "Big-O of finding all pairs that sum to target in array (naive):",
        choices: ["$O(n^2)$", "$O(n)$", "$O(n\\log n)$", "$O(1)$"], correct: 0,
        solution: S({ c: "Check every pair: nested loops.", s: ["With hash set: $O(n)$ — store complements seen so far."], a: "$O(n^2)$ naive" }), ref: "p.415" },
    ],
  };

  let added = 0;
  for (const ch of QUESTION_BANK.chapters) {
    if (P[ch.id]) {
      ch.questions.push(...P[ch.id]);
      added += P[ch.id].length;
    }
  }
  const total = QUESTION_BANK.chapters.reduce((s, c) => s + c.questions.length, 0);
  console.log(`Pack 7: +${added} → bank total ${total}`);
})();
