// FE Electrical Question Bank — Extension Pack 4 (~170 problems)
(function () {
  if (typeof QUESTION_BANK === "undefined" || typeof S === "undefined") return;

  const P = {
    // ====================== Ch 1: Math — +18 ======================
    1: [
      { q: "$|3-j4|$ = ", choices: ["$5$", "$1$", "$25$", "$7$"], correct: 0,
        solution: S({ c: "Magnitude: $|a+jb|=\\sqrt{a^2+b^2}$.", s: ["$\\sqrt{9+16}=\\sqrt{25}=5$."], a: "$5$", v: "3-4-5 right triangle." }), ref: "Handbook p.36" },
      { q: "Complex number in exponential form: $z = 5\\angle 60°$ as $re^{j\\theta}$ with $\\theta$ in radians:",
        choices: ["$5 e^{j\\pi/3}$", "$5 e^{j60}$", "$5 e^{j\\pi/6}$", "$60 e^{j5}$"], correct: 0,
        solution: S({ c: "Convert degrees to radians: $\\theta_{rad}=\\theta_{deg}\\cdot \\pi/180$.", s: ["$60° = \\pi/3$ rad. So $5e^{j\\pi/3}$."], a: "$5 e^{j\\pi/3}$", v: "Euler: $e^{j\\pi/3}=\\cos 60°+j\\sin 60°=0.5+j0.866$." }), ref: "Handbook p.36" },
      { q: "Solve $|2x-1| = 5$:",
        choices: ["$x=3$ or $x=-2$", "$x=3$ only", "$x=2$ only", "$x=-3$ or $x=2$"], correct: 0,
        solution: S({ c: "Absolute value: $|y|=k \\Rightarrow y=\\pm k$.", s: ["$2x-1=5 \\Rightarrow x=3$.", "$2x-1=-5 \\Rightarrow x=-2$."], a: "$x=3, -2$", v: "Check: $|2(3)-1|=5$ ✓; $|2(-2)-1|=5$ ✓" }), ref: "Handbook p.35" },
      { q: "$\\tan^{-1}(1) + \\tan^{-1}(\\sqrt{3})$ = (in degrees)",
        choices: ["$105°$", "$120°$", "$90°$", "$135°$"], correct: 0,
        solution: S({ c: "$\\tan^{-1}(1)=45°$, $\\tan^{-1}(\\sqrt{3})=60°$. Sum.", s: ["$45+60=105°$."], a: "$105°$", v: "Common reference angles to memorize: $\\tan(30°)=1/\\sqrt{3}$, $\\tan(60°)=\\sqrt{3}$." }), ref: "Handbook p.37" },
      { q: "Find $y$ when $\\ln y = 2.5$:",
        choices: ["$y \\approx 12.18$", "$y=2.5$", "$y \\approx 0.082$", "$y=5$"], correct: 0,
        solution: S({ c: "Inverse of $\\ln$: $y = e^{2.5}$.", s: ["$e^{2.5} \\approx 12.18$."], a: "$y \\approx 12.18$", v: "$e \\approx 2.718$, so $e^{2.5}$ is between $e^2 \\approx 7.39$ and $e^3 \\approx 20.1$ ✓" }), ref: "Handbook p.36" },
      { q: "Matrix $A = \\begin{pmatrix}1&2&3\\\\0&4&5\\\\0&0&6\\end{pmatrix}$. Determinant:",
        choices: ["$24$", "$30$", "$0$", "$1$"], correct: 0,
        solution: S({ c: "Triangular matrix: $|A|$ = product of diagonal.", s: ["$1 \\cdot 4 \\cdot 6 = 24$."], a: "$24$", v: "Upper triangular here. Lower triangular: same rule." }), ref: "Handbook p.57" },
      { q: "If $A = \\begin{pmatrix}1&0\\\\0&-2\\end{pmatrix}$, $A^3 = $",
        choices: ["$\\begin{pmatrix}1&0\\\\0&-8\\end{pmatrix}$", "$\\begin{pmatrix}3&0\\\\0&-6\\end{pmatrix}$", "$\\begin{pmatrix}1&0\\\\0&8\\end{pmatrix}$", "Cannot compute"], correct: 0,
        solution: S({ c: "Diagonal matrix raised to power: cube each diagonal entry.", s: ["$1^3 = 1$, $(-2)^3 = -8$."], a: "$\\begin{pmatrix}1&0\\\\0&-8\\end{pmatrix}$", v: "General: $D^n$ for diagonal $D$ = diag of $d_i^n$." }), ref: "Handbook p.57" },
      { q: "Transpose of $A = \\begin{pmatrix}1&2\\\\3&4\\\\5&6\\end{pmatrix}$:",
        choices: ["$\\begin{pmatrix}1&3&5\\\\2&4&6\\end{pmatrix}$", "Same matrix", "$\\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$", "Negative"], correct: 0,
        solution: S({ c: "Transpose: rows ↔ columns. $3\\times 2 \\to 2\\times 3$.", s: ["First row of $A^T$ is first column of $A$: $(1,3,5)$.", "Second row of $A^T$ is second column of $A$: $(2,4,6)$."], a: "$\\begin{pmatrix}1&3&5\\\\2&4&6\\end{pmatrix}$", v: "$(A^T)^T = A$ always." }), ref: "Handbook p.57" },
      { q: "$f(x) = x^3 - 3x$. Find local minimum value.",
        choices: ["$-2$ (at $x=1$)", "$0$", "$2$ (at $x=-1$)", "$-1$"], correct: 0,
        solution: S({ c: "Set $f'=0$, check $f''$.", s: ["$f'(x) = 3x^2 - 3 = 0 \\Rightarrow x = \\pm 1$.", "$f''(x) = 6x$. $f''(1) = 6 > 0$ → min at $x=1$. $f''(-1)=-6<0$ → max at $x=-1$.", "$f(1) = 1 - 3 = -2$."], a: "$-2$", v: "$f(-1) = -1+3 = 2$ is the local max ✓" }), ref: "Handbook p.47-49" },
      { q: "$\\int e^{-2x} dx$:",
        choices: ["$-\\frac{1}{2}e^{-2x} + C$", "$e^{-2x} + C$", "$-2 e^{-2x} + C$", "$\\frac{1}{2}e^{-2x} + C$"], correct: 0,
        solution: S({ c: "$\\int e^{ax}dx = e^{ax}/a + C$.", s: ["With $a=-2$: $-\\frac{1}{2}e^{-2x} + C$."], a: "$-\\frac{1}{2}e^{-2x} + C$", v: "Derivative back: $-\\frac{1}{2}(-2)e^{-2x} = e^{-2x}$ ✓" }), ref: "Handbook p.49" },
      { q: "Indefinite integral $\\int 1/(x^2+1) dx$:",
        choices: ["$\\tan^{-1}(x) + C$", "$\\ln(x^2+1) + C$", "$1/(x+1) + C$", "$x/(x+1) + C$"], correct: 0,
        solution: S({ c: "Standard form: $\\int 1/(x^2+1)dx = \\arctan x + C$.", s: ["Memorize this standard form."], a: "$\\arctan x + C$", v: "More general: $\\int 1/(x^2+a^2)dx = (1/a)\\arctan(x/a) + C$." }), ref: "Handbook p.49" },
      { q: "ODE $y'' + 9y = 0$ general solution:",
        choices: ["$C_1\\cos 3x + C_2\\sin 3x$", "$C_1 e^{3x} + C_2 e^{-3x}$", "$C_1 + C_2 x$", "$C e^{-9x}$"], correct: 0,
        solution: S({ c: "Char eq $r^2+9=0$ → $r = \\pm 3j$ (purely imaginary). Solution: $C_1\\cos\\beta x + C_2\\sin\\beta x$ with $\\beta=3$.", s: ["No damping ($\\alpha=0$) → pure oscillation."], a: "$C_1\\cos 3x + C_2\\sin 3x$", v: "Frequency $\\omega = 3$ rad/x; period $T = 2\\pi/3$." }), ref: "Handbook p.55" },
      { q: "$\\nabla f$ for $f(x,y,z) = x^2 y + z^3$ at $(1,2,1)$:",
        choices: ["$(4, 1, 3)$", "$(2, 1, 3)$", "$(4, 1, 1)$", "$(2, 0, 1)$"], correct: 0,
        solution: S({ c: "Gradient = $(\\partial f/\\partial x, \\partial f/\\partial y, \\partial f/\\partial z)$.", s: ["$\\partial f/\\partial x = 2xy = 2(1)(2) = 4$.", "$\\partial f/\\partial y = x^2 = 1$.", "$\\partial f/\\partial z = 3z^2 = 3(1) = 3$.", "$\\nabla f = (4, 1, 3)$."], a: "$(4, 1, 3)$", v: "Gradient points in direction of steepest increase." }), ref: "Handbook p.38" },
      { q: "$\\sum_{k=0}^{4} 2^k$ = ",
        choices: ["$31$", "$32$", "$15$", "$16$"], correct: 0,
        solution: S({ c: "Geometric sum: $\\sum_{k=0}^{n} r^k = (r^{n+1}-1)/(r-1)$.", s: ["$1 + 2 + 4 + 8 + 16 = 31$.", "Or: $(2^5-1)/(2-1) = 31$."], a: "$31$", v: "n-bit binary max value: $2^n - 1$. Familiar pattern." }), ref: "Handbook p.50" },
      { q: "Average rate of change of $f(x) = x^2$ on $[1, 4]$:",
        choices: ["$5$", "$15$", "$3$", "$9$"], correct: 0,
        solution: S({ c: "Avg rate = $(f(b) - f(a))/(b - a)$.", s: ["$(16 - 1)/(4 - 1) = 15/3 = 5$."], a: "$5$", v: "Mean Value Theorem: there exists $c \\in (1,4)$ where $f'(c) = 5$, i.e., $2c = 5 \\Rightarrow c = 2.5$ ✓" }), ref: "Handbook p.47" },
      { q: "$\\dfrac{d}{dx}[\\arctan(x)]$ = ",
        choices: ["$\\dfrac{1}{1+x^2}$", "$\\dfrac{1}{\\sqrt{1-x^2}}$", "$\\dfrac{-1}{1+x^2}$", "$\\sec^2 x$"], correct: 0,
        solution: S({ c: "Standard derivative.", s: ["Memorize: $\\dfrac{d}{dx}\\arctan x = \\dfrac{1}{1+x^2}$."], a: "$1/(1+x^2)$", v: "Inverse function rule: if $y = \\arctan x$, $\\tan y = x$, differentiate: $\\sec^2 y\\,dy/dx = 1$, $dy/dx = \\cos^2 y = 1/(1+\\tan^2 y) = 1/(1+x^2)$." }), ref: "Handbook p.47" },
      { q: "Slope of tangent to $y = \\ln x$ at $x = e$:",
        choices: ["$1/e$", "$1$", "$0$", "$e$"], correct: 0,
        solution: S({ c: "$y' = 1/x$. Evaluate at $x = e$.", s: ["$y'(e) = 1/e \\approx 0.368$."], a: "$1/e$", v: "$\\ln$ has decreasing slope; at $x=1$, slope = 1; at $x=e$, slope = $1/e$." }), ref: "Handbook p.47" },
      { q: "$\\lim_{x \\to 0} \\dfrac{1-\\cos x}{x^2}$ = ",
        choices: ["$1/2$", "$0$", "$1$", "Does not exist"], correct: 0,
        solution: S({ c: "L'Hopital twice or use $1 - \\cos x \\approx x^2/2$ for small $x$.", s: ["L'Hopital: $\\lim \\dfrac{\\sin x}{2x}$. Apply again: $\\lim \\dfrac{\\cos x}{2} = 1/2$."], a: "$1/2$", v: "Famous limit. Equivalent to Taylor series: $\\cos x = 1 - x^2/2 + ...$" }), ref: "Handbook p.47" },
    ],

    // ====================== Ch 2: Probability — +12 ======================
    2: [
      { q: "Mean of {3, 5, 7, 9}:", choices: ["$6$", "$5$", "$7$", "$24$"], correct: 0,
        solution: S({ c: "Sum/count.", s: ["$(3+5+7+9)/4 = 24/4 = 6$."], a: "$6$", v: "Equally spaced numbers → mean = median = midpoint." }), ref: "Handbook p.63" },
      { q: "Mode of {2, 3, 3, 4, 5, 5, 5}:", choices: ["$5$", "$3$", "$4$", "Multiple"], correct: 0,
        solution: S({ c: "Mode = most frequent value.", s: ["5 appears 3 times; 3 appears 2 times; others once.", "Mode = 5."], a: "$5$", v: "Bimodal: two equally-frequent modes. None: all different." }), ref: "Handbook p.63" },
      { q: "P(at least one head in 3 fair coin flips):",
        choices: ["$7/8$", "$1/8$", "$1/2$", "$3/8$"], correct: 0,
        solution: S({ c: "$P(\\ge 1) = 1 - P(\\text{none})$. Easier than direct sum.", s: ["$P(\\text{0 heads}) = (1/2)^3 = 1/8$.", "$P(\\ge 1) = 1 - 1/8 = 7/8$."], a: "$7/8$", v: "General: probability of any event happening at least once → use complement." }), ref: "Handbook p.65" },
      { q: "Conditional prob $P(B|A) = 0.6$, $P(A) = 0.4$. $P(A \\cap B)$ = ",
        choices: ["$0.24$", "$0.6$", "$0.4$", "$1.0$"], correct: 0,
        solution: S({ c: "$P(A \\cap B) = P(A) \\cdot P(B|A)$.", s: ["$0.4 \\cdot 0.6 = 0.24$."], a: "$0.24$" }), ref: "Handbook p.65" },
      { q: "Quality control: 100 widgets, 3 defective. Probability 1 random widget is defective:",
        choices: ["$0.03$", "$0.3$", "$0.97$", "$3$"], correct: 0,
        solution: S({ c: "P = favorable/total.", s: ["$P = 3/100 = 0.03$."], a: "$0.03 (3\\%)$" }), ref: "Handbook p.64" },
      { q: "Continuous uniform distribution on $[0, 10]$. Mean and std dev:",
        choices: ["$\\mu=5, \\sigma\\approx 2.89$", "$\\mu=5, \\sigma=10/12$", "$\\mu=10, \\sigma=5$", "$\\mu=5, \\sigma=5$"], correct: 0,
        solution: S({ c: "Uniform $U(a,b)$: $\\mu = (a+b)/2$, $\\sigma^2 = (b-a)^2/12$.", s: ["$\\mu = 5$.", "$\\sigma^2 = 100/12 = 8.33$.", "$\\sigma = \\sqrt{8.33} \\approx 2.89$."], a: "$\\mu=5, \\sigma\\approx 2.89$" }), ref: "Handbook p.67" },
      { q: "Poisson process with rate $\\lambda = 2$ events/hour. P(exactly 3 events in 1 hour):",
        choices: ["$\\approx 0.180$", "$\\approx 0.667$", "$\\approx 0.135$", "$\\approx 0.500$"], correct: 0,
        solution: S({ c: "Poisson: $P(k) = \\lambda^k e^{-\\lambda}/k!$.", s: ["$P(3) = 2^3 e^{-2}/3! = 8(0.1353)/6 = 0.1804$."], a: "$\\approx 0.180$", v: "Mean of Poisson is $\\lambda$; here mean = 2, so 3 is slightly above mean." }), ref: "Handbook p.66" },
      { q: "Standard error of mean: $\\sigma=10$, $n=25$. SE = ",
        choices: ["$2$", "$10$", "$0.4$", "$25$"], correct: 0,
        solution: S({ c: "$SE = \\sigma/\\sqrt{n}$.", s: ["$10/\\sqrt{25} = 10/5 = 2$."], a: "$2$" }), ref: "Handbook p.69" },
      { q: "Linear regression: $y = mx + b$. Best fit minimizes:",
        choices: ["Sum of squared residuals", "Sum of residuals", "Maximum residual", "Slope"], correct: 0,
        solution: S({ c: "Least squares: minimize $\\sum (y_i - \\hat{y}_i)^2$.", s: ["Squaring penalizes large errors more.", "Yields normal equations for slope and intercept."], a: "Sum of squared residuals", v: "Robust regression uses absolute deviations to be less sensitive to outliers." }), ref: "Handbook p.69" },
      { q: "Correlation coefficient range:",
        choices: ["$-1 \\le r \\le 1$", "$0 \\le r \\le 1$", "$-\\infty \\le r \\le \\infty$", "$0 \\le r \\le 100$"], correct: 0,
        solution: S({ c: "Pearson correlation: -1 (perfect negative) to +1 (perfect positive). 0 = no linear correlation.", s: ["Sign indicates direction.", "Magnitude indicates strength."], a: "$[-1, 1]$", v: "$r^2$ (coefficient of determination): fraction of variance explained." }), ref: "Handbook p.69" },
      { q: "Z-score $z = 2$ corresponds to:",
        choices: ["$\\approx 97.7\\%$ percentile", "$\\approx 95\\%$", "$\\approx 50\\%$", "$\\approx 99.7\\%$"], correct: 0,
        solution: S({ c: "Standard normal: $P(Z \\le 2) = 0.9772$.", s: ["By empirical rule: ~95% within $\\pm 2\\sigma$. Above 0 is half of remaining... actually $P(Z \\le 2) = 0.9772$."], a: "$\\approx 97.7\\%$ percentile", v: "Memorize: $z=1 \\to 84\\%$, $z=2 \\to 97.5\\%$, $z=3 \\to 99.85\\%$." }), ref: "Handbook p.67" },
      { q: "Hypothesis testing: $\\alpha = 0.05$. Reject $H_0$ when:",
        choices: ["p-value < 0.05", "p-value > 0.05", "Statistic = 0", "Statistic > $\\alpha$"], correct: 0,
        solution: S({ c: "$\\alpha$ = significance level (type I error rate). Reject null if observed result is too unlikely under it.", s: ["p-value: probability of observing data as extreme as we did, assuming $H_0$ true.", "If p < $\\alpha$: reject $H_0$ (evidence against null)."], a: "p < 0.05", v: "Common $\\alpha$ = 0.05 (5% false-positive rate). Stricter: 0.01 or 0.001 in critical applications." }), ref: "Handbook p.70" },
    ],

    // ====================== Ch 3: Ethics — +5 ======================
    3: [
      { q: "An engineer is asked to falsify test data. They should:",
        choices: ["Refuse, document, and report through proper channels", "Comply and report later", "Modify slightly", "Resign quietly"], correct: 0,
        solution: S({ c: "Falsifying data violates the engineer's duty to be truthful and to protect public welfare.", s: ["Document the request.", "Refuse to falsify.", "Report to supervisor or licensing board as appropriate."], a: "Refuse and report.", v: "Whistleblower protections exist in most jurisdictions." }), ref: "Handbook p.5" },
      { q: "A licensed PE acts as expert witness in litigation. They must:",
        choices: ["Be impartial and truthful regardless of who hired them", "Support the hiring party", "Stay silent on weaknesses", "Match opposing expert"], correct: 0,
        solution: S({ c: "Engineer testimony must be objective. Bias toward client/employer violates code.", s: ["Engineers are educators in court — must explain facts impartially.", "Even adversely affecting hiring party's case if facts demand."], a: "Be impartial and truthful.", v: "Some PE codes explicitly require this; misrepresentation can result in license suspension." }), ref: "Handbook p.5" },
      { q: "Continuing education for licensed PEs is typically:",
        choices: ["Required (specific PDH hours per renewal)", "Optional", "Only for management", "Not regulated"], correct: 0,
        solution: S({ c: "Most US states require Professional Development Hours (PDH) annually or per renewal cycle to maintain license.", s: ["Typical: 15-30 PDH per 2-year renewal.", "Some require ethics-specific hours."], a: "Required (varies by state)", v: "NCEES tracks PDH for engineers practicing across state lines." }), ref: "Handbook p.11" },
      { q: "An engineer's primary professional obligation is to:",
        choices: ["Public health, safety, and welfare", "Employer", "Profession", "Self"], correct: 0,
        solution: S({ c: "NCEES Model Rule #1.", s: ["Hierarchy: Public > Client/Employer > Profession > Self."], a: "Public", v: "Sometimes called the engineer's 'paramount obligation'." }), ref: "Handbook p.5" },
      { q: "Whose stamp/seal goes on engineering drawings?",
        choices: ["The PE who prepared or thoroughly reviewed the work", "Senior partner", "Owner", "Any licensed person"], correct: 0,
        solution: S({ c: "Stamp = professional responsibility for the work.", s: ["Stamping someone else's unreviewed work = plan stamping (prohibited).", "Only stamp work you have prepared or fully checked."], a: "Engineer in responsible charge.", v: "Some firms have multiple PEs each responsible for different sections of large projects." }), ref: "Handbook p.5" },
    ],

    // ====================== Ch 4: Econ — +10 ======================
    4: [
      { q: "$P = \\$5000$, $i = 6\\%$/yr, $n = 10$ yrs. Future value:",
        choices: ["$\\approx \\$8954$", "$\\$8000$", "$\\$5300$", "$\\$5600$"], correct: 0,
        solution: S({ c: "$F = P(1+i)^n$.", s: ["$(1.06)^{10} = 1.7908$.", "$F = 5000 \\cdot 1.7908 = 8954$."], a: "$\\approx \\$8954$" }), ref: "Handbook p.230" },
      { q: "Annual deposits of $1000 for 20 years at 7%. Future value:",
        choices: ["$\\approx \\$40{,}995$", "$\\$20{,}000$", "$\\$70{,}000$", "$\\$33{,}066$"], correct: 0,
        solution: S({ c: "$F = A \\cdot (F/A, i, n)$ where $(F/A) = ((1+i)^n - 1)/i$.", s: ["$(1.07)^{20} = 3.8697$.", "$(F/A) = (3.8697 - 1)/0.07 = 40.995$.", "$F = 1000 \\cdot 40.995 = \\$40{,}995$."], a: "$\\approx \\$40{,}995$", v: "Compounding earns more than just $\\$20{,}000$ principal — interest on interest." }), ref: "Handbook p.231" },
      { q: "Sinking fund: save annually to accumulate $\\$50{,}000$ in 5 years at $i=6\\%$. Annual deposit:",
        choices: ["$\\approx \\$8870$", "$\\$10{,}000$", "$\\$5000$", "$\\$12{,}500$"], correct: 0,
        solution: S({ c: "$A = F/(F/A, i, n)$.", s: ["$(F/A, 6\\%, 5) = (1.06^5 - 1)/0.06 = 5.6371$.", "$A = 50000/5.6371 = 8869.8$."], a: "$\\approx \\$8870$" }), ref: "Handbook p.231" },
      { q: "Net present value (NPV) decision rule:",
        choices: ["Accept if NPV > 0", "Accept if NPV = 0", "Accept if NPV < 0", "Reject all"], correct: 0,
        solution: S({ c: "NPV > 0 means project earns more than required rate of return.", s: ["NPV = 0: break-even, indifferent.", "NPV < 0: lose money compared to alternative investment at $i$."], a: "Accept if NPV > 0", v: "When choosing between mutually exclusive projects: pick highest NPV." }), ref: "Handbook p.232" },
      { q: "MARR (minimum attractive rate of return) is:",
        choices: ["Threshold below which projects are rejected", "Maximum possible return", "Market rate only", "Always zero"], correct: 0,
        solution: S({ c: "MARR = company's required rate of return, often based on cost of capital + risk premium.", s: ["Reject projects with IRR < MARR.", "Set above safest alternative (e.g., T-bills) by enough to compensate for project risk."], a: "Minimum required return.", v: "Typical MARR: 10-15% for mature firms; higher for startups/risky industries." }), ref: "Handbook p.232" },
      { q: "Depreciation reduces:",
        choices: ["Taxable income (saving taxes)", "Asset value to zero immediately", "Loan principal", "Revenue"], correct: 0,
        solution: S({ c: "Depreciation is a non-cash expense that reduces reported income for tax purposes.", s: ["Tax savings: $D \\times t$ where $t$ = tax rate.", "Methods: straight-line, MACRS, double-declining."], a: "Taxable income → tax savings", v: "After-tax cash flow analysis includes depreciation tax shield." }), ref: "Handbook p.230" },
      { q: "Payback period for $\\$10{,}000$ investment returning $\\$2{,}500$/yr:",
        choices: ["4 years (simple)", "5 years", "$25\\%$", "Cannot tell"], correct: 0,
        solution: S({ c: "Simple payback = initial cost / annual return (ignores time value).", s: ["$10{,}000/2{,}500 = 4$ years."], a: "4 years", v: "Discounted payback would be longer because future $\\$2500$ is worth less now." }), ref: "Handbook p.232" },
      { q: "Tax credit vs tax deduction (simplistic): a $\\$1000$ credit saves $\\$1000$; a $\\$1000$ deduction saves:",
        choices: ["$\\$1000 \\times$ marginal tax rate", "$\\$1000$", "Nothing", "Twice as much"], correct: 0,
        solution: S({ c: "Credit: dollar-for-dollar reduction in tax owed. Deduction: reduces taxable income, save (deduction × tax rate).", s: ["E.g., 25% bracket: $\\$1000$ deduction saves $\\$250$."], a: "Deduction × tax rate", v: "Credits typically more valuable than equivalent deductions." }), ref: "Handbook p.230" },
      { q: "If MARR is 10%, project with IRR of 8% should be:",
        choices: ["Rejected", "Accepted", "Studied more", "Postponed"], correct: 0,
        solution: S({ c: "Accept if IRR > MARR.", s: ["IRR 8% < MARR 10% → reject (project doesn't meet minimum threshold)."], a: "Rejected" }), ref: "Handbook p.232" },
      { q: "Real interest rate from nominal 8% and inflation 3%:",
        choices: ["$\\approx 4.85\\%$", "$5\\%$", "$11\\%$", "$2.7\\%$"], correct: 0,
        solution: S({ c: "Fisher: $(1+i_r) = (1+i_n)/(1+f)$.", s: ["$(1+i_r) = 1.08/1.03 = 1.04854$.", "$i_r = 4.854\\%$."], a: "$\\approx 4.85\\%$", v: "Approximation $i_r \\approx i_n - f = 5\\%$ is close but not exact." }), ref: "Handbook p.230" },
    ],

    // ====================== Ch 5: Materials — +4 ======================
    5: [
      { q: "Aluminum vs copper as a conductor: aluminum has ___ conductivity:",
        choices: ["Lower (about 60% of Cu)", "Higher", "Same", "Zero"], correct: 0,
        solution: S({ c: "Cu $\\sigma \\approx 5.96\\times 10^7$ S/m. Al $\\sigma \\approx 3.5\\times 10^7$ S/m. Ratio: 58.7%.", s: ["Al is lighter and cheaper, used in transmission lines.", "Cu is more conductive, used in motor windings, buildings."], a: "Al ≈ 60% of Cu", v: "Same current handling: aluminum wire needs to be ~1.6× larger cross-section." }), ref: "Handbook p.354" },
      { q: "Ohm's law in terms of current density:",
        choices: ["$\\vec{J} = \\sigma\\vec{E}$", "$V = IR$", "$\\vec{F} = q\\vec{E}$", "$P = IV$"], correct: 0,
        solution: S({ c: "Microscopic form: current density proportional to E-field via conductivity.", s: ["Integrated form: $V = IR$ (over a uniform conductor of length $L$, area $A$, where $R = \\rho L/A$).", "Choice C is Lorentz force, not Ohm's law."], a: "$\\vec{J} = \\sigma\\vec{E}$", v: "$\\sigma$ is the constant of proportionality. In free space, no current flows (vacuum has $\\sigma = 0$)." }), ref: "Handbook p.354" },
      { q: "Power dissipation density in resistive material:",
        choices: ["$\\sigma E^2$ (W/m³)", "$\\sigma E$", "$E/\\sigma$", "$\\rho J$"], correct: 0,
        solution: S({ c: "Power per unit volume: $p = \\vec{J}\\cdot\\vec{E} = \\sigma E^2$.", s: ["Integrated over volume: total $P = I^2 R$."], a: "$\\sigma E^2$ (W/m³)", v: "Material limits set max E-field (else dielectric breakdown)." }), ref: "Handbook p.354" },
      { q: "Magnetic permeability of free space $\\mu_0$:",
        choices: ["$4\\pi \\times 10^{-7}$ H/m", "$8.85 \\times 10^{-12}$ F/m", "$1$", "$3 \\times 10^8$"], correct: 0,
        solution: S({ c: "Memorize: $\\mu_0 = 4\\pi \\times 10^{-7}$ H/m ≈ $1.257 \\times 10^{-6}$ H/m.", s: ["Choice B is $\\varepsilon_0$ (permittivity).", "These define $c = 1/\\sqrt{\\mu_0 \\varepsilon_0}$."], a: "$\\mu_0 = 4\\pi \\times 10^{-7}$ H/m", v: "Modern definitions (post-2019 SI redefinition) make $\\mu_0$ measured, not exactly $4\\pi \\times 10^{-7}$, but very close." }), ref: "Handbook p.355" },
    ],

    // ====================== Ch 6: Circuits — +20 ======================
    6: [
      { q: "Source transformation: $V_{Th} = 24$ V, $R_{Th} = 8$Ω → Norton equivalent:",
        choices: ["$I_N = 3$ A, $R_N = 8$Ω", "$I_N = 24$ A", "$I_N = 8$ A", "$I_N = 3$ A, $R_N = 1/8$Ω"], correct: 0,
        solution: S({ c: "$I_N = V_{Th}/R_{Th}$, $R_N = R_{Th}$.", s: ["$I_N = 24/8 = 3$ A.", "$R_N = 8\\ \\Omega$."], a: "$I_N = 3$ A, $R_N = 8\\ \\Omega$" }), ref: "Handbook p.357" },
      { q: "If $I = 2$ A flows through a 5Ω resistor for 30 s, energy dissipated:",
        choices: ["$600$ J", "$60$ J", "$300$ J", "$10$ J"], correct: 0,
        solution: S({ c: "$W = Pt = I^2 R \\cdot t$.", s: ["$P = 4 \\cdot 5 = 20$ W.", "$W = 20 \\cdot 30 = 600$ J."], a: "$600$ J" }), ref: "Handbook p.356" },
      { q: "Power delivered by an ideal 12V battery if it pushes 0.5 A through external circuit:",
        choices: ["$6$ W", "$24$ W", "$12$ W", "$2$ W"], correct: 0,
        solution: S({ c: "$P = VI$ for ideal source.", s: ["$P = 12 \\cdot 0.5 = 6$ W."], a: "$6$ W" }), ref: "Handbook p.356" },
      { q: "Internal resistance of 9V battery: drops to 8.5V when delivering 0.5 A. Internal R:",
        choices: ["$1\\ \\Omega$", "$0.5\\ \\Omega$", "$17\\ \\Omega$", "$0.05\\ \\Omega$"], correct: 0,
        solution: S({ c: "$V_{terminal} = V_{EMF} - I R_{internal}$.", s: ["Drop: $9 - 8.5 = 0.5$ V over internal R at 0.5 A.", "$R_{internal} = 0.5/0.5 = 1\\ \\Omega$."], a: "$1\\ \\Omega$", v: "Why batteries warm up under load — $I^2 R$ heat dissipated internally." }), ref: "Handbook p.357" },
      { q: "Three 4Ω resistors all in parallel:",
        choices: ["$4/3 \\approx 1.33\\ \\Omega$", "$12\\ \\Omega$", "$4\\ \\Omega$", "$1\\ \\Omega$"], correct: 0,
        solution: S({ c: "Equal R in parallel: $R/n$.", s: ["$4/3 = 1.33\\ \\Omega$."], a: "$1.33\\ \\Omega$" }), ref: "Handbook p.356" },
      { q: "Current through 6Ω in parallel with 12Ω (combined fed by 30V source):",
        choices: ["$I_{6}=5$ A, $I_{12}=2.5$ A", "Both 5 A", "$I_6=2.5$ A", "Both 2.5 A"], correct: 0,
        solution: S({ c: "Same voltage (30V) across both parallel branches. $I = V/R$.", s: ["$I_6 = 30/6 = 5$ A.", "$I_{12} = 30/12 = 2.5$ A."], a: "$I_6 = 5$ A, $I_{12} = 2.5$ A", v: "Total: 7.5 A. $R_{eq} = 30/7.5 = 4\\ \\Omega$ — between 6 and 12 ✓" }), ref: "Handbook p.356" },
      { q: "RL transient: starting from $i=0$ at $t=0$, with $V=12$ V, $R=4\\ \\Omega$, $L=8$ mH. Steady-state current:",
        choices: ["$3$ A", "$12$ A", "$0.375$ A", "$8$ mA"], correct: 0,
        solution: S({ c: "At steady state, inductor acts as wire (no voltage across L). $I = V/R$.", s: ["$I_{ss} = 12/4 = 3$ A."], a: "$3$ A", v: "Time constant: $\\tau = L/R = 0.008/4 = 2$ ms." }), ref: "Handbook p.358" },
      { q: "RC circuit time constant in seconds, $R = 100$ Ω, $C = 1$ mF:",
        choices: ["$0.1$ s", "$10^{-4}$ s", "$1$ s", "$10$ s"], correct: 0,
        solution: S({ c: "$\\tau = RC$. Watch units: 1 mF = $10^{-3}$ F.", s: ["$\\tau = 100 \\cdot 10^{-3} = 0.1$ s."], a: "$0.1$ s" }), ref: "Handbook p.358" },
      { q: "60 Hz AC, peak $V_m = 170$ V. RMS value:",
        choices: ["$120$ V", "$170$ V", "$240$ V", "$85$ V"], correct: 0,
        solution: S({ c: "$V_{RMS} = V_m/\\sqrt{2}$.", s: ["$170/1.414 \\approx 120$ V."], a: "$120$ V", v: "Standard US household — $170$ V peak = $120$ V RMS." }), ref: "Handbook p.360" },
      { q: "$V_m = 100$, $I_m = 5$ at $\\theta = 0°$ phase between. Average power:",
        choices: ["$250$ W", "$500$ W", "$70.7$ W", "$0$ W"], correct: 0,
        solution: S({ c: "$P_{avg} = (V_m I_m / 2) \\cos\\theta = V_{rms} I_{rms} \\cos\\theta$.", s: ["$P = 100 \\cdot 5 \\cdot \\cos 0° / 2 = 500/2 = 250$ W."], a: "$250$ W", v: "$pf = 1$ (resistive) → all of apparent power is real." }), ref: "Handbook p.362" },
      { q: "Capacitor in DC steady state acts as:",
        choices: ["Open circuit", "Short", "$1\\ \\Omega$", "Variable resistor"], correct: 0,
        solution: S({ c: "At DC, $\\omega = 0$ → $Z_C = 1/(j\\omega C) \\to \\infty$ (open).", s: ["Inductor at DC: $Z_L = j\\omega L = 0$ (short)."], a: "Open circuit", v: "These limiting behaviors simplify DC analysis of mixed circuits." }), ref: "Handbook p.358" },
      { q: "Inductor in DC steady state:",
        choices: ["Short circuit (acts as wire)", "Open circuit", "Capacitor", "Negative R"], correct: 0,
        solution: S({ c: "DC: $Z_L = j\\omega L = 0$.", s: ["No voltage across (V = L di/dt; with i constant, V = 0)."], a: "Short", v: "Useful for finding DC operating points: replace caps with opens, inductors with shorts." }), ref: "Handbook p.358" },
      { q: "Three sources in parallel: 12V, 12V, 12V all ideal. Output across all:",
        choices: ["$12$ V (but circulating currents possible)", "$36$ V", "$4$ V", "Indeterminate"], correct: 0,
        solution: S({ c: "Ideal sources at same V: voltage is 12V, but real (non-ideal) sources may have circulating current.", s: ["Practical: never parallel ideal voltage sources without small series R to limit current."], a: "12 V (with caveat about circulating)", v: "Why batteries in parallel need close matching and small internal R." }), ref: "Handbook p.356" },
      { q: "Three resistors equal value 10Ω each: one config gives 30Ω, another gives 3.33Ω. Which is which?",
        choices: ["Series→30, Parallel→3.33", "Reversed", "Both 10", "Cannot tell"], correct: 0,
        solution: S({ c: "Series adds; parallel: R/n.", s: ["Series: $10+10+10=30\\ \\Omega$.", "Parallel: $10/3 = 3.33\\ \\Omega$."], a: "Series=30, Parallel=3.33" }), ref: "Handbook p.356" },
      { q: "Impedance $Z = 30 + j40$. Convert to polar:",
        choices: ["$50\\angle 53.13°$", "$70\\angle 45°$", "$50\\angle 30°$", "$30\\angle 53°$"], correct: 0,
        solution: S({ c: "$|Z| = \\sqrt{R^2 + X^2}$, $\\theta = \\arctan(X/R)$.", s: ["$|Z| = \\sqrt{900+1600} = 50$.", "$\\theta = \\arctan(40/30) = 53.13°$."], a: "$50\\angle 53.13°$", v: "3-4-5 right triangle with phase angle of 53.13°." }), ref: "Handbook p.360" },
      { q: "Apparent power S in VA when $V = 240$ V RMS, $I = 10$ A RMS:",
        choices: ["$2400$ VA", "$1697$ VA", "$48{,}000$ VA", "$24$ kW"], correct: 0,
        solution: S({ c: "$|S| = V_{rms} \\cdot I_{rms}$ (RMS values).", s: ["$|S| = 240 \\cdot 10 = 2400$ VA."], a: "$2400$ VA", v: "Units: VA (apparent), W (real), VAR (reactive)." }), ref: "Handbook p.362" },
      { q: "Two impedances in series: $Z_1 = 10\\angle 0°$, $Z_2 = 10\\angle 90°$. Total:",
        choices: ["$10 + j10$ = $14.14\\angle 45°$", "$20\\angle 45°$", "$100\\angle 90°$", "$0$"], correct: 0,
        solution: S({ c: "Series Z adds as complex numbers (convert to rectangular first if needed).", s: ["$Z_1 = 10$, $Z_2 = j10$.", "Sum: $10 + j10 = 14.14\\angle 45°$."], a: "$14.14\\angle 45°$" }), ref: "Handbook p.360" },
      { q: "Inductive impedance at 1 kHz: $L = 1$ mH. $X_L$:",
        choices: ["$\\approx 6.28\\ \\Omega$", "$1\\ \\Omega$", "$1000\\ \\Omega$", "$0.159$"], correct: 0,
        solution: S({ c: "$X_L = \\omega L = 2\\pi f L$.", s: ["$X_L = 2\\pi(1000)(10^{-3}) = 2\\pi \\approx 6.283\\ \\Omega$."], a: "$\\approx 6.28\\ \\Omega$" }), ref: "Handbook p.360" },
      { q: "Capacitive impedance at 1 kHz: $C = 1$ µF. $X_C$:",
        choices: ["$\\approx 159\\ \\Omega$", "$1000\\ \\Omega$", "$0.159\\ \\Omega$", "$6.28\\ \\Omega$"], correct: 0,
        solution: S({ c: "$X_C = 1/(\\omega C) = 1/(2\\pi f C)$.", s: ["$X_C = 1/(2\\pi \\cdot 1000 \\cdot 10^{-6}) = 1/(6.28 \\times 10^{-3}) \\approx 159\\ \\Omega$."], a: "$\\approx 159\\ \\Omega$", v: "Cap reactance decreases with frequency; inductor reactance increases." }), ref: "Handbook p.360" },
      { q: "AC source $v = 100\\cos\\omega t$ V, current $i = 10\\cos(\\omega t - 30°)$. Real power:",
        choices: ["$\\approx 433$ W", "$1000$ W", "$500$ W", "$250$ W"], correct: 0,
        solution: S({ c: "$P = (V_m I_m / 2) \\cos\\theta$.", s: ["$\\theta = 30°$ (current lags 30°).", "$P = (100 \\cdot 10/2)\\cos 30° = 500 \\cdot 0.866 = 433$ W."], a: "$\\approx 433$ W" }), ref: "Handbook p.362" },
    ],

    // ====================== Ch 7: Linear Systems — +10 ======================
    7: [
      { q: "Laplace of $u(t)$ (unit step):",
        choices: ["$1/s$", "$1$", "$s$", "$\\delta(s)$"], correct: 0,
        solution: S({ c: "Standard.", s: ["$\\mathcal{L}\\{u(t)\\} = \\int_0^\\infty 1 \\cdot e^{-st} dt = 1/s$."], a: "$1/s$" }), ref: "Handbook p.56" },
      { q: "Laplace of $\\delta(t)$ (unit impulse):",
        choices: ["$1$", "$1/s$", "$0$", "$s$"], correct: 0,
        solution: S({ c: "Standard.", s: ["Sifting property: $\\int_0^\\infty \\delta(t) e^{-st} dt = e^0 = 1$."], a: "$1$" }), ref: "Handbook p.56" },
      { q: "Transfer function of an integrator:",
        choices: ["$H(s) = 1/s$", "$H(s) = s$", "$H(s) = 1$", "$H(s) = s^2$"], correct: 0,
        solution: S({ c: "Integration in time = division by $s$ in Laplace.", s: ["Differentiation: multiplication by $s$."], a: "$1/s$", v: "Pure integrator has infinite DC gain — accumulates indefinitely." }), ref: "Handbook p.56" },
      { q: "First-order LPF $H(s) = K/(s + a)$. Time constant:",
        choices: ["$\\tau = 1/a$", "$\\tau = a$", "$\\tau = K$", "$\\tau = a/K$"], correct: 0,
        solution: S({ c: "Standard form: $H(s) = K/(s + 1/\\tau)$. Compare.", s: ["Time constant = inverse of pole magnitude."], a: "$\\tau = 1/a$" }), ref: "Handbook p.366" },
      { q: "Bandwidth of $H(s) = 10/(s+5)$:",
        choices: ["$5$ rad/s", "$10$ rad/s", "$1$ rad/s", "$50$ rad/s"], correct: 0,
        solution: S({ c: "1st-order LPF: $-3$dB at pole frequency.", s: ["Pole at $s=-5$, so $\\omega_c = 5$ rad/s."], a: "$5$ rad/s", v: "In Hz: $5/(2\\pi) \\approx 0.796$ Hz." }), ref: "Handbook p.366" },
      { q: "Phase at DC of $H(s) = 1/(s+1)$:",
        choices: ["$0°$", "$-45°$", "$-90°$", "$90°$"], correct: 0,
        solution: S({ c: "At $\\omega = 0$: $H(0) = 1/1 = 1$ (real). Phase = 0°.", s: ["As $\\omega$ increases, phase moves toward $-90°$ (1st-order LPF)."], a: "$0°$" }), ref: "Handbook p.366" },
      { q: "Resonant frequency of $H(s) = 1/(s^2 + 0.1 s + 100)$:",
        choices: ["$10$ rad/s", "$100$ rad/s", "$1$ rad/s", "$5$ rad/s"], correct: 0,
        solution: S({ c: "Standard 2nd-order: $s^2 + 2\\zeta\\omega_n s + \\omega_n^2$. Compare: $\\omega_n^2 = 100 \\Rightarrow \\omega_n = 10$.", s: ["Damping: $2\\zeta\\omega_n = 0.1 \\Rightarrow \\zeta = 0.005$ (very lightly damped)."], a: "$10$ rad/s", v: "Low damping → sharp resonance peak. $Q = 1/(2\\zeta) = 100$." }), ref: "Handbook p.366" },
      { q: "If $H(s) = 1/[(s+1)(s+2)]$, time-domain impulse response includes:",
        choices: ["$e^{-t}$ and $e^{-2t}$ terms", "Sine and cosine", "Constant only", "Ramp"], correct: 0,
        solution: S({ c: "Each pole contributes an exponential in time. Pole at $s = -a \\to e^{-at}$.", s: ["Two distinct poles → two exponentials."], a: "$e^{-t}, e^{-2t}$", v: "Partial fractions decomposition gives the coefficients." }), ref: "Handbook p.56" },
      { q: "Group delay of $H(s) = e^{-2s}$ (pure delay):",
        choices: ["$2$ seconds (constant)", "Variable", "$1/2$ second", "$0$"], correct: 0,
        solution: S({ c: "$e^{-as}$ in Laplace = time shift by $a$ seconds. Constant group delay = $a$.", s: ["Linear phase: $\\angle H(j\\omega) = -2\\omega$.", "Group delay: $-d\\phi/d\\omega = 2$."], a: "$2$ s", v: "Ideal delay preserves waveform shape — important in audio/communications." }), ref: "Handbook p.366" },
      { q: "$H(s) = 5(s+2)/[(s+1)(s+3)]$. Number of zeros and poles:",
        choices: ["1 zero, 2 poles", "2 zeros, 2 poles", "1 zero, 1 pole", "0 zeros, 3 poles"], correct: 0,
        solution: S({ c: "Zeros: roots of numerator. Poles: roots of denominator.", s: ["Numerator $s+2$ has 1 zero at $s=-2$.", "Denominator has 2 poles at $s=-1, -3$."], a: "1 zero, 2 poles", v: "When poles > zeros, called 'proper'; ensures system is causal/realizable." }), ref: "Handbook p.365" },
    ],

    // ====================== Ch 8: Signal — +10 ======================
    8: [
      { q: "Energy of a discrete signal $x[n] = \\{1, 2, -1\\}$:",
        choices: ["$6$", "$2$", "$0$", "$3$"], correct: 0,
        solution: S({ c: "Energy: $E = \\sum |x[n]|^2$.", s: ["$1^2 + 2^2 + (-1)^2 = 1 + 4 + 1 = 6$."], a: "$6$" }), ref: "Handbook p.376" },
      { q: "Periodic signal has __ Fourier series:",
        choices: ["Discrete spectrum", "Continuous spectrum", "No spectrum", "Random spectrum"], correct: 0,
        solution: S({ c: "Periodic signals decompose into discrete harmonics — frequencies are integer multiples of fundamental.", s: ["Aperiodic signals → continuous Fourier transform."], a: "Discrete spectrum (harmonics)", v: "Square wave: contains odd harmonics 1, 3, 5, ... of fundamental." }), ref: "Handbook p.371-376" },
      { q: "Convolution in time = ___ in frequency:",
        choices: ["Multiplication", "Convolution again", "Addition", "Differentiation"], correct: 0,
        solution: S({ c: "Convolution theorem: $\\mathcal{F}\\{x * h\\} = X(\\omega) H(\\omega)$.", s: ["This is why we describe filters via $H(\\omega)$ — just multiply the input spectrum.", "Reverse: multiplication in time = convolution in frequency."], a: "Multiplication", v: "Saves computation: FFT-based fast convolution." }), ref: "Handbook p.376" },
      { q: "A 1st order HPF cutoff at 1 kHz, signal at 100 Hz, gain:",
        choices: ["$\\approx -20$ dB (attenuated)", "$0$ dB", "$+20$ dB", "$-3$ dB"], correct: 0,
        solution: S({ c: "HPF: opposite of LPF. Frequencies below cutoff attenuated at 20 dB/decade.", s: ["From 100 Hz to 1 kHz is 1 decade below cutoff: -20 dB."], a: "$-20$ dB" }), ref: "Handbook p.375" },
      { q: "Notch filter is used to:",
        choices: ["Remove a narrow band of frequencies", "Pass all frequencies", "Amplify one frequency", "Generate signals"], correct: 0,
        solution: S({ c: "Notch filter: very narrow stop band. Typical use: remove 60 Hz mains hum from audio/instrumentation.", s: ["Inverse of bandpass.", "Implemented with parallel RLC or twin-T networks."], a: "Remove specific narrow band" }), ref: "Handbook p.375" },
      { q: "Nyquist plot for an integrator $H(s) = 1/s$ starts at:",
        choices: ["$-j\\infty$ (low freq)", "Origin", "$+j\\infty$", "$1$"], correct: 0,
        solution: S({ c: "At $\\omega \\to 0^+$: $H(j\\omega) = 1/(j\\omega) \\to -j\\infty$.", s: ["At $\\omega \\to \\infty$: $H \\to 0$.", "Nyquist trace: pure imaginary axis from $-j\\infty$ to 0."], a: "$-j\\infty$", v: "Phase always $-90°$ for ideal integrator." }), ref: "Handbook p.366" },
      { q: "Quantization noise power of an n-bit ADC over full-scale range $V_{FS}$:",
        choices: ["$\\Delta^2/12$ where $\\Delta = V_{FS}/2^n$", "$\\Delta$", "$V_{FS}/n$", "$2^n$"], correct: 0,
        solution: S({ c: "Uniform quantization: error uniformly distributed over $\\pm \\Delta/2$. Variance = $\\Delta^2/12$.", s: ["For full-scale sinusoid signal of variance $V_{FS}^2/8$: SQNR ≈ $1.5 \\cdot 2^{2n}$ ≈ $6.02n + 1.76$ dB."], a: "$\\Delta^2/12$" }), ref: "Handbook p.375" },
      { q: "Sample-and-hold output between samples is:",
        choices: ["Constant (held value)", "Linearly interpolated", "Zero", "Smoothed"], correct: 0,
        solution: S({ c: "ZOH (zero-order hold): holds each sample's value until the next sample.", s: ["Effect: introduces $\\text{sinc}$-shape frequency response.", "Followed by reconstruction filter to smooth."], a: "Constant value" }), ref: "Handbook p.375" },
      { q: "FIR vs IIR filter primary difference:",
        choices: ["FIR has finite impulse response; IIR has infinite", "Same thing", "IIR is non-causal", "FIR is unstable"], correct: 0,
        solution: S({ c: "FIR: output depends only on inputs (feedforward). IIR: output depends on past outputs (feedback).", s: ["FIR: always stable, linear phase possible, more taps for same selectivity.", "IIR: efficient (fewer coefficients), but stability concerns."], a: "FIR finite, IIR infinite response" }), ref: "Handbook p.376" },
      { q: "Discrete-time signal $x[n]$ shifted: $x[n - 2]$ means:",
        choices: ["Delayed by 2 samples", "Advanced by 2", "Doubled", "Halved"], correct: 0,
        solution: S({ c: "Subtraction in index = delay. $x[n-k]$ is $x$ delayed by $k$ samples.", s: ["Z-transform: multiplication by $z^{-k}$.", "$x[n+k]$ would be advance."], a: "Delayed by 2 samples" }), ref: "Handbook p.376" },
    ],

    // ====================== Ch 9: Electronics — +20 ======================
    9: [
      { q: "Common-mode gain of an ideal op-amp:",
        choices: ["Zero", "$\\infty$", "$1$", "Depends"], correct: 0,
        solution: S({ c: "Ideal op-amp: infinite differential gain, ZERO common-mode gain → CMRR = ∞.", s: ["Real op-amps have small but non-zero common-mode gain."], a: "Zero" }), ref: "Handbook p.380" },
      { q: "Slew rate of $1$ V/µs: max frequency for full-scale 10V signal:",
        choices: ["$\\approx 15.9$ kHz", "$1$ MHz", "$100$ Hz", "$10$ MHz"], correct: 0,
        solution: S({ c: "Max sinusoid frequency: $f_{max} = \\text{SR}/(2\\pi V_{peak})$.", s: ["$SR = 10^6$ V/s, $V_{peak} = 10$ V.", "$f_{max} = 10^6/(2\\pi \\cdot 10) = 15915$ Hz $\\approx 15.9$ kHz."], a: "$\\approx 15.9$ kHz", v: "Above this, output cannot keep up with input — slew-rate distortion (triangulation)." }), ref: "Handbook p.380" },
      { q: "BJT $\\beta = 50$. $I_C = 100$ mA. $I_B$:",
        choices: ["$2$ mA", "$5000$ mA", "$50$ mA", "$0.05$ mA"], correct: 0,
        solution: S({ c: "$I_B = I_C/\\beta$.", s: ["$100/50 = 2$ mA."], a: "$2$ mA" }), ref: "Handbook p.384" },
      { q: "$V_{CE,sat}$ of typical BJT in saturation:",
        choices: ["$\\approx 0.2$ V", "$0.7$ V", "$5$ V", "$0$ V"], correct: 0,
        solution: S({ c: "Saturated BJT: low $V_{CE}$, both junctions forward-biased.", s: ["Memorize: $V_{CE,sat} \\approx 0.2$ V."], a: "$0.2$ V" }), ref: "Handbook p.384" },
      { q: "Class B audio amp: efficiency limit:",
        choices: ["$\\approx 78.5\\%$ ($\\pi/4$)", "$50\\%$", "$25\\%$", "$100\\%$"], correct: 0,
        solution: S({ c: "Class B: two transistors each conduct 180°. Theoretical max efficiency = $\\pi/4 \\approx 78.5\\%$.", s: ["Real Class B: 60-70% due to losses.", "Class AB: slightly less efficient but eliminates crossover distortion."], a: "$\\approx 78.5\\%$" }), ref: "Handbook p.384" },
      { q: "Op-amp comparator output:",
        choices: ["Saturated high or low (no feedback)", "Linear", "Zero", "Random"], correct: 0,
        solution: S({ c: "Comparator: op-amp without feedback. Tiny input difference → output rails (saturates).", s: ["$v_+ > v_-$: output = $+V_{sat}$.", "$v_+ < v_-$: output = $-V_{sat}$.", "Used in: zero-crossing detector, peak detector, A/D conversion."], a: "Saturated rails" }), ref: "Handbook p.380" },
      { q: "MOSFET threshold voltage $V_{th}$ for nMOS in enhancement:",
        choices: ["Positive (typically 0.5-2 V)", "Negative", "Zero", "$10$ V"], correct: 0,
        solution: S({ c: "Enhancement nMOS: $V_{th} > 0$. Needs positive gate voltage to form channel.", s: ["pMOS enhancement: $V_{th} < 0$.", "Depletion mode: opposite signs."], a: "Positive (0.5-2 V typical)" }), ref: "Handbook p.386" },
      { q: "Op-amp $A_{OL} = 10^5$, $A_{CL} = 100$. Loop gain $A\\beta$:",
        choices: ["$10^3 - 1 \\approx 10^3$", "$10^5$", "$100$", "$10^7$"], correct: 0,
        solution: S({ c: "$A_{CL} = A_{OL}/(1 + A\\beta)$. Solve: $A\\beta = A_{OL}/A_{CL} - 1 \\approx 10^5/100 - 1 = 999$.", s: ["Equivalently: $1/\\beta \\approx 100$ (closed-loop gain)."], a: "$\\approx 10^3$" }), ref: "Handbook p.380" },
      { q: "Increasing feedback ($\\beta$ larger) does what to bandwidth?",
        choices: ["Widens bandwidth (gain-BW tradeoff)", "Narrows", "No effect", "Causes oscillation"], correct: 0,
        solution: S({ c: "Gain-bandwidth product is constant. More feedback (smaller closed-loop gain) → larger BW.", s: ["$f_{cl} \\times A_{cl} = $ GBW.", "Reducing gain extends usable frequency range."], a: "Widens BW" }), ref: "Handbook p.380" },
      { q: "Schottky diode advantage over Si diode:",
        choices: ["Lower forward drop (~0.3 V)", "Higher voltage", "Slower switching", "Cheaper always"], correct: 0,
        solution: S({ c: "Schottky: metal-semiconductor junction. Lower $V_F$ (~0.3 V vs 0.7 V), faster switching.", s: ["Used in: rectifiers (lower loss), high-frequency switching, RF detection."], a: "Lower $V_F$ ≈ 0.3 V" }), ref: "Handbook p.383" },
      { q: "Power dissipation in a switching MOSFET:",
        choices: ["$P_{cond} = I^2 R_{ds,on}$ + switching losses", "$IV$ always", "Zero in saturation", "$V_{ds}^2/R$"], correct: 0,
        solution: S({ c: "Switching losses: $P_{sw} = \\frac{1}{2} V_{ds} I (t_{rise} + t_{fall}) f_{sw}$. Plus conduction $I^2 R_{ds,on}$.", s: ["Hard switching: significant power lost in transitions.", "Soft switching (zero-voltage/current): reduces losses."], a: "Conduction + switching losses" }), ref: "Handbook p.386" },
      { q: "Output impedance of an emitter follower:",
        choices: ["Very low (≈ $r_e$ + $R_S/\\beta$)", "Very high", "$R_C$", "Zero exactly"], correct: 0,
        solution: S({ c: "Emitter follower acts as buffer: high $Z_{in}$, low $Z_{out}$.", s: ["$Z_{out} \\approx r_e + R_{source}/(\\beta+1)$.", "Typical: a few ohms to tens of ohms."], a: "Very low" }), ref: "Handbook p.384" },
      { q: "Two transistors in cascode configuration provide:",
        choices: ["High gain + high bandwidth (Miller reduced)", "Lower gain", "Just isolation", "Lower input Z"], correct: 0,
        solution: S({ c: "Cascode = CE + CB stack. CB stage isolates output from input — Miller capacitance impact reduced.", s: ["Same gain as CE alone but much wider bandwidth.", "Common in RF amplifiers and op-amp internals."], a: "High gain + wide BW" }), ref: "Handbook p.384" },
      { q: "An op-amp is configured as integrator. Input is square wave. Output is:",
        choices: ["Triangle wave", "Square wave inverted", "Sine wave", "Zero"], correct: 0,
        solution: S({ c: "Integral of square wave (constant during each half) is linear ramp → triangle.", s: ["Conversely: differentiator of triangle would give square."], a: "Triangle wave" }), ref: "Handbook p.380" },
      { q: "Voltage regulator IC like 7805 has minimum input voltage of about:",
        choices: ["$\\sim 7$ V (dropout 2 V above output)", "$5$ V", "$12$ V", "$0$ V"], correct: 0,
        solution: S({ c: "Linear regulators need 'dropout voltage' = $V_{in,min} - V_{out}$.", s: ["7805: standard ~2 V dropout, so $V_{in} \\ge 7$ V.", "LDO variants: 0.3-0.5 V dropout."], a: "$\\sim 7$ V" }), ref: "Handbook p.383" },
      { q: "Common-collector (emitter-follower): voltage gain ≈",
        choices: ["$\\approx 1$ (just under)", "$-\\beta$", "$+\\beta R_C$", "$0$"], correct: 0,
        solution: S({ c: "CC: input at base, output at emitter, follows input.", s: ["$A_v = R_E/(R_E + r_e) \\approx 1$ when $R_E \\gg r_e$."], a: "$\\approx 1$" }), ref: "Handbook p.384" },
      { q: "BJT amplifier with low input impedance:",
        choices: ["Common-Base (CB)", "Common-Emitter", "Common-Collector", "Class A"], correct: 0,
        solution: S({ c: "CB has $Z_{in} \\approx r_e \\approx 25\\ \\Omega/I_E$ (mA). Very low.", s: ["CE: $\\beta r_e$ medium.", "CC (emitter follower): $\\beta R_E$ high."], a: "Common-Base", v: "CB used in RF for matching to 50-ohm transmission lines." }), ref: "Handbook p.384" },
      { q: "Op-amp instrumentation amplifier: 3 op-amps with specific R network. Used for:",
        choices: ["High-CMRR differential amplification", "Logarithmic conversion", "Filtering", "Comparators"], correct: 0,
        solution: S({ c: "INA: very high CMRR (>100 dB), high $Z_{in}$, single gain resistor.", s: ["Used in: bridge sensors (strain gauges, thermocouples), medical instrumentation (ECG).", "Common ICs: INA125, AD620."], a: "High-CMRR diff amp" }), ref: "Handbook p.380" },
      { q: "Voltage-controlled oscillator (VCO) frequency is proportional to:",
        choices: ["Control voltage (linearly)", "Power supply", "Temperature", "Capacitor charge"], correct: 0,
        solution: S({ c: "VCO: output frequency varies linearly with input control voltage.", s: ["Key element of PLL (phase-locked loop).", "Used in FM modulation, frequency synthesis, clock generation."], a: "Control voltage" }), ref: "Handbook p.383" },
      { q: "Pulse-width modulation (PWM) duty cycle:",
        choices: ["Ratio of ON time to total period", "Frequency", "Amplitude", "Phase"], correct: 0,
        solution: S({ c: "Duty cycle = $t_{on}/T$ (0 to 100%).", s: ["50% duty = symmetric square wave.", "Used in motor speed control, switching power supplies, LED dimming."], a: "$t_{on}/T$" }), ref: "Handbook p.383" },
    ],

    // ====================== Ch 10: Power — +15 ======================
    10: [
      { q: "120 V single phase, 1500 W resistive load. Current:",
        choices: ["$12.5$ A", "$1500$ A", "$0.08$ A", "$180$ A"], correct: 0,
        solution: S({ c: "$P = VI$ for resistive (pf=1).", s: ["$I = P/V = 1500/120 = 12.5$ A."], a: "$12.5$ A", v: "Hair dryer or coffee maker — typical 1500W appliance." }), ref: "Handbook p.362" },
      { q: "3-phase delta-connected source with $V_{LL}=480$ V. Each phase voltage:",
        choices: ["$480$ V", "$277$ V", "$240$ V", "$830$ V"], correct: 0,
        solution: S({ c: "Delta: $V_{phase} = V_{LL}$.", s: ["Delta connection has phase voltage = line voltage."], a: "$480$ V" }), ref: "Handbook p.363" },
      { q: "Power dissipated in line resistance: 3-phase 120 A line current, 0.1 Ω per line:",
        choices: ["$\\approx 4320$ W (sum of 3 lines)", "$\\approx 1440$ W (one line)", "$\\approx 14.4$ W", "Zero"], correct: 0,
        solution: S({ c: "Each line: $P = I^2 R$. Three lines.", s: ["Per line: $120^2 \\cdot 0.1 = 1440$ W.", "Three lines: $3 \\cdot 1440 = 4320$ W."], a: "$\\approx 4320$ W", v: "Why higher voltage → lower current → lower I²R losses." }), ref: "Handbook p.363" },
      { q: "Single-phase 240 V/120 V split-phase service is common in:",
        choices: ["US residential", "European residential", "Industrial only", "Aviation"], correct: 0,
        solution: S({ c: "US homes: 240V split into two 120V hot legs by center-tapped transformer.", s: ["240V for high-power loads (dryer, range, AC).", "120V for normal outlets, lights."], a: "US residential" }), ref: "Handbook p.363" },
      { q: "Capacitor bank used for PF correction is connected in:",
        choices: ["Parallel with load", "Series with load", "Series with source", "Replaces load"], correct: 0,
        solution: S({ c: "Shunt capacitors provide leading VAR to offset lagging VAR of inductive loads.", s: ["Improves PF without affecting load operation.", "Sometimes switched in steps via contactors."], a: "Parallel" }), ref: "Handbook p.363" },
      { q: "Star-Delta motor starter purpose:",
        choices: ["Reduce starting current (~1/3 of direct-online)", "Increase starting torque", "Speed control", "Reverse rotation"], correct: 0,
        solution: S({ c: "Starts in Y (lower phase voltage → lower inrush), switches to Δ (full power) once near speed.", s: ["Reduces starting current to ~1/3 of DOL.", "Starting torque also reduced to 1/3 — only suitable for light loads at start."], a: "Reduce starting current" }), ref: "Handbook p.365" },
      { q: "Open-circuit test of transformer measures:",
        choices: ["Core (iron) losses primarily", "Winding (copper) losses", "Insulation", "Voltage ratio only"], correct: 0,
        solution: S({ c: "OC test: rated V on one side, other open. Only excitation current flows → core losses dominate.", s: ["Short-circuit test: low V, rated I, primarily copper losses.", "Together: characterize the transformer model."], a: "Core losses" }), ref: "Handbook p.364" },
      { q: "Per-unit (pu) impedance of a transformer is the same on both sides because:",
        choices: ["Base impedance also transforms by $a^2$", "Real impedance is the same", "Both sides have same windings", "Coincidence"], correct: 0,
        solution: S({ c: "Actual Z transforms by $a^2$. Base Z also transforms by $a^2$ (since $Z_{base} = V^2/S$ and V scales by $a$). Ratio = same.", s: ["Why per-unit is preferred for multi-voltage systems — uniform numbers across all parts."], a: "Base also scales" }), ref: "Handbook p.363-364" },
      { q: "Synchronous generator frequency depends on:",
        choices: ["Rotor speed and pole count", "Voltage only", "Load only", "Stator winding"], correct: 0,
        solution: S({ c: "$f = (poles \\cdot rpm)/120$ for synchronous machines.", s: ["Constant speed → constant frequency.", "Grid-tie requires synchronization (frequency, voltage, phase match)."], a: "Speed × poles" }), ref: "Handbook p.365" },
      { q: "DC machine commutator function:",
        choices: ["Converts AC in armature to DC at brushes (or vice versa)", "Generates field", "Bearings", "Cooling"], correct: 0,
        solution: S({ c: "Rotating armature generates AC; commutator reverses connections to brushes every half-rotation → unidirectional DC at brushes.", s: ["In DC motor: brush-fed DC current is commutated → torque in same direction."], a: "AC↔DC rectification" }), ref: "Handbook p.365" },
      { q: "Three-phase induction motor reversal:",
        choices: ["Swap any two of the three lines", "Reverse polarity", "Change frequency", "Reduce voltage"], correct: 0,
        solution: S({ c: "Swapping two phases reverses the rotating magnetic field direction → motor reverses.", s: ["Single-phase induction: must reconfigure capacitor or use start winding reversal."], a: "Swap two phases" }), ref: "Handbook p.365" },
      { q: "Power factor of pure inductor:",
        choices: ["$0$ (lagging)", "$1$", "$0.5$", "$-1$"], correct: 0,
        solution: S({ c: "Pure inductor: V leads I by 90°. $\\cos 90° = 0$.", s: ["All power is reactive, none real."], a: "$0$ lagging" }), ref: "Handbook p.362" },
      { q: "Wye-connected load: line voltage 480V, line current 25 A, pf 0.85. Total real power:",
        choices: ["$\\approx 17.66$ kW", "$\\approx 20$ kW", "$\\approx 12$ kW", "$\\approx 8.4$ kW"], correct: 0,
        solution: S({ c: "$P = \\sqrt{3} V_{LL} I_L \\cos\\theta$.", s: ["$\\sqrt{3} \\cdot 480 \\cdot 25 = 20{,}785$ VA.", "$P = 20785 \\cdot 0.85 = 17{,}667$ W."], a: "$\\approx 17.67$ kW" }), ref: "Handbook p.363" },
      { q: "Voltage drop across transmission line = ?",
        choices: ["$I \\cdot (R + jX)$", "$I \\cdot R$", "$I \\cdot X$", "$IL$"], correct: 0,
        solution: S({ c: "Line has resistance and inductive reactance. Drop is complex.", s: ["Short line: $\\Delta V = I \\cdot Z_{line}$ approximately.", "Long line: distributed parameters; use ABCD model."], a: "$I(R + jX)$" }), ref: "Handbook p.363" },
      { q: "Transformer rated 100 kVA, 13.8 kV / 480 V. Short-circuit current (primary, rated impedance 5%):",
        choices: ["$\\approx 145$ A (20× rated)", "Rated 7.25 A", "$\\approx 7.25$ A", "$10$ A"], correct: 0,
        solution: S({ c: "Short-circuit current $\\approx I_{rated}/Z_{pu}$.", s: ["$I_{rated} = 100000/13800 = 7.25$ A.", "$I_{SC} = 7.25/0.05 = 145$ A (20× rated)."], a: "$\\approx 145$ A", v: "Why fault current calculations matter — selecting protective devices that can interrupt these currents safely." }), ref: "Handbook p.364" },
    ],

    // ====================== Ch 11: EM — +8 ======================
    11: [
      { q: "Electrostatic force between two 1 C charges 1 m apart:",
        choices: ["$\\approx 9 \\times 10^9$ N (HUGE)", "$1$ N", "$10^{-9}$ N", "$8.99$ N"], correct: 0,
        solution: S({ c: "Coulomb: $F = k_e q_1 q_2/r^2$.", s: ["$F = 8.99\\times 10^9 \\cdot 1 \\cdot 1 / 1^2 = 8.99\\times 10^9$ N."], a: "$\\sim 9\\times 10^9$ N", v: "1 C is enormous — typical charges are µC or smaller." }), ref: "Handbook p.355" },
      { q: "Electric field of a point charge at distance $r$:",
        choices: ["$E = k_e q/r^2$", "$E = k_e q/r$", "$E = q r$", "$E = qr^2$"], correct: 0,
        solution: S({ c: "From Coulomb force: $E = F/q_{test} = k_e q/r^2$.", s: ["Falls off as $1/r^2$ — same as gravity.", "Line charge: $E \\propto 1/r$. Plane charge: $E$ constant."], a: "$k_e q/r^2$" }), ref: "Handbook p.355" },
      { q: "Voltage between parallel plates with E-field $E$ and separation $d$:",
        choices: ["$V = Ed$", "$V = E/d$", "$V = Ed^2$", "$V = E + d$"], correct: 0,
        solution: S({ c: "Uniform field: $V = \\int E \\, dx = Ed$ for distance $d$.", s: ["$E = V/d$ inversely."], a: "$V = Ed$" }), ref: "Handbook p.355" },
      { q: "Faraday's law: induced EMF =",
        choices: ["$-d\\Phi/dt$", "$+d\\Phi/dt$", "$\\Phi$", "$1/\\Phi$"], correct: 0,
        solution: S({ c: "EMF = $-d\\Phi_B/dt$. Negative sign (Lenz's law): induced current opposes the flux change.", s: ["Time-varying flux through loop → EMF around loop."], a: "$-d\\Phi/dt$", v: "Generators, transformers, induction motors all rely on this." }), ref: "Handbook p.355" },
      { q: "Inductance of a solenoid: $N = 200$, $l = 10$ cm, $A = 5$ cm², $\\mu_r = 1$:",
        choices: ["$\\approx 25\\ \\mu$H", "$25$ mH", "$2.5$ H", "$250$ µH"], correct: 0,
        solution: S({ c: "$L = \\mu_0 \\mu_r N^2 A/l$.", s: ["$L = (4\\pi\\times 10^{-7})(200)^2 (5\\times 10^{-4})/(0.1)$.", "$= (4\\pi\\times 10^{-7})(40000)(0.005) = 4\\pi\\times 10^{-5} \\cdot 0.1 \\approx 2.51\\times 10^{-5}$ H = 25 µH."], a: "$\\approx 25$ µH" }), ref: "Handbook p.355" },
      { q: "EM wave impedance of free space:",
        choices: ["$\\approx 377\\ \\Omega$", "$50\\ \\Omega$", "$1\\ \\Omega$", "$0$"], correct: 0,
        solution: S({ c: "$\\eta_0 = \\sqrt{\\mu_0/\\varepsilon_0} \\approx 377\\ \\Omega$ (or $120\\pi$).", s: ["Memorized value.", "In dielectric: $\\eta = \\eta_0/\\sqrt{\\varepsilon_r}$ (for non-magnetic)."], a: "$\\approx 377\\ \\Omega$" }), ref: "Handbook p.368" },
      { q: "Wavelength of microwave at 2.45 GHz (microwave oven):",
        choices: ["$\\approx 12.2$ cm", "$30$ cm", "$1$ m", "$1$ mm"], correct: 0,
        solution: S({ c: "$\\lambda = c/f$.", s: ["$\\lambda = 3\\times 10^8/2.45\\times 10^9 = 0.1224$ m = 12.24 cm."], a: "$\\approx 12.2$ cm", v: "Why microwave ovens have hot/cold spots ~6 cm apart (half-wavelength standing waves)." }), ref: "Handbook p.368" },
      { q: "For a TEM wave in dielectric ($\\varepsilon_r = 4$): speed:",
        choices: ["$\\approx 1.5\\times 10^8$ m/s", "$3\\times 10^8$ m/s", "$3\\times 10^8/4$", "$3\\times 10^8 \\cdot 4$"], correct: 0,
        solution: S({ c: "$v = c/\\sqrt{\\varepsilon_r}$ (non-magnetic).", s: ["$v = c/2 = 1.5\\times 10^8$ m/s."], a: "$\\approx 1.5\\times 10^8$ m/s", v: "Coax with PE dielectric ($\\varepsilon_r \\approx 2.25$): velocity factor ~0.66." }), ref: "Handbook p.368" },
    ],

    // ====================== Ch 12: Control — +12 ======================
    12: [
      { q: "Open-loop step response of $G(s) = 1/(s+2)$:",
        choices: ["$(1 - e^{-2t})/2 \\cdot u(t)$", "$e^{-2t}$", "Constant 0.5", "Sine wave"], correct: 0,
        solution: S({ c: "Y(s) = G(s)/s. Partial fractions.", s: ["$Y(s) = 1/[s(s+2)] = (1/2)[1/s - 1/(s+2)]$.", "Inverse: $(1/2)(1 - e^{-2t})$."], a: "$(1-e^{-2t})/2$", v: "Final value 0.5 = DC gain × step amplitude." }), ref: "Handbook p.366" },
      { q: "Steady-state error for type-2 system to ramp input:",
        choices: ["$0$", "$1/K_v$", "Infinite", "$1/K_p$"], correct: 0,
        solution: S({ c: "Type-2 has 2 integrators → handles ramp perfectly.", s: ["Type-0 step: $1/(1+K_p)$. Type-1 step: 0; ramp: $1/K_v$. Type-2 ramp: 0; parabola: $1/K_a$."], a: "$0$" }), ref: "Handbook p.366" },
      { q: "Maximum overshoot $M_p$ for $\\zeta = 0.6$:",
        choices: ["$\\approx 9.5\\%$", "$0\\%$", "$50\\%$", "$25\\%$"], correct: 0,
        solution: S({ c: "$M_p = e^{-\\pi\\zeta/\\sqrt{1-\\zeta^2}}$.", s: ["$\\zeta = 0.6$: $\\sqrt{1-0.36} = 0.8$. $\\pi(0.6/0.8) = 2.36$. $e^{-2.36} \\approx 0.0948$."], a: "$\\approx 9.5\\%$", v: "$\\zeta=0.7$ → ~4.6%. $\\zeta=0.5$ → ~16%. Linear in pre-exp expression but exponential overall." }), ref: "Handbook p.366" },
      { q: "Pole at origin in open-loop transfer means:",
        choices: ["Type-1 system (integrator)", "Type-0", "Unstable", "Resonant"], correct: 0,
        solution: S({ c: "Number of $s=0$ poles in open loop = system type.", s: ["Affects steady-state error formulas."], a: "Type-1" }), ref: "Handbook p.366" },
      { q: "Routh array first column has all positive entries. Conclusion:",
        choices: ["All poles in LHP — stable", "Unstable", "Marginal", "Cannot tell"], correct: 0,
        solution: S({ c: "No sign changes → no RHP poles → stable.", s: ["Special cases: row of zeros (marginal) or zero in first column (auxiliary equation)."], a: "Stable" }), ref: "Handbook p.365" },
      { q: "Lead compensator pole-zero relationship:",
        choices: ["Zero closer to origin than pole", "Pole closer to origin", "Pole = zero", "Both at origin"], correct: 0,
        solution: S({ c: "Lead: $(s+z)/(s+p)$ with $z < p$. Adds positive phase between $z$ and $p$.", s: ["Lag: $z > p$. Lead-lag: combines both."], a: "$z < p$" }), ref: "Handbook p.366" },
      { q: "PID controller derivative term effect on:",
        choices: ["Adds damping, predicts future, but amplifies noise", "Eliminates SS error", "Increases gain only", "No effect"], correct: 0,
        solution: S({ c: "$K_d \\cdot de/dt$: responds to rate of error change.", s: ["Adds damping: anticipates overshoot.", "Drawback: amplifies high-freq noise.", "Often filtered (PID with derivative filter)."], a: "Adds damping" }), ref: "Handbook p.366" },
      { q: "A system has $\\omega_n = 5$ rad/s, $\\zeta = 0.5$. Damped frequency:",
        choices: ["$\\approx 4.33$ rad/s", "$5$ rad/s", "$2.5$ rad/s", "$10$ rad/s"], correct: 0,
        solution: S({ c: "$\\omega_d = \\omega_n \\sqrt{1-\\zeta^2}$.", s: ["$\\sqrt{1-0.25} = 0.866$.", "$\\omega_d = 5 \\cdot 0.866 = 4.33$ rad/s."], a: "$\\approx 4.33$ rad/s" }), ref: "Handbook p.366" },
      { q: "Bode plot magnitude slope of pure $K$ (gain only):",
        choices: ["$0$ dB/dec (flat)", "$-20$ dB/dec", "$+20$ dB/dec", "Variable"], correct: 0,
        solution: S({ c: "Constant in $s$ → no slope in Bode.", s: ["Phase contribution: 0° (assuming K > 0)."], a: "0 dB/dec" }), ref: "Handbook p.366" },
      { q: "Differentiator $H(s) = s$: Bode magnitude:",
        choices: ["$+20$ dB/dec (rising)", "Flat", "$-20$ dB/dec", "Constant"], correct: 0,
        solution: S({ c: "$|H(j\\omega)| = \\omega$. dB: $20\\log\\omega$. Slope: 20 dB/dec.", s: ["Phase: $+90°$ (constant)."], a: "+20 dB/dec" }), ref: "Handbook p.366" },
      { q: "Closed-loop poles all in LHP. Conclusion:",
        choices: ["Closed-loop stable", "Open loop unstable", "Marginal", "Insufficient info"], correct: 0,
        solution: S({ c: "Stability of closed-loop is determined by closed-loop pole locations.", s: ["Open-loop instability doesn't preclude closed-loop stability — feedback can stabilize."], a: "Stable" }), ref: "Handbook p.365" },
      { q: "Block diagram: input $X$ → $G_1$ → summing junction (- feedback from $H_1$) → $G_2$ → output $Y$. Transfer function:",
        choices: ["$Y/X = G_1 G_2/(1 + G_1 H_1)$ ... depends on where feedback taps", "Always $G_1 G_2$", "Always $1/G$", "$G + H$"], correct: 0,
        solution: S({ c: "Use block diagram reduction rules. Negative feedback around the front part: $G_1/(1+G_1 H_1)$. Then series with $G_2$.", s: ["Depends on exact topology. The given structure: $G_1/(1+G_1 H_1) \\cdot G_2$."], a: "Depends; using given: $G_1 G_2/(1+G_1 H_1)$" }), ref: "Handbook p.365" },
    ],

    // ====================== Ch 13: Comm — +10 ======================
    13: [
      { q: "PCM telephone channel: 8000 samples/s × 8 bits = ",
        choices: ["$64$ kbps", "$8$ kbps", "$1$ Mbps", "$56$ kbps"], correct: 0,
        solution: S({ c: "Bit rate = samples/s × bits/sample.", s: ["$8000 \\cdot 8 = 64{,}000$ bps = 64 kbps."], a: "$64$ kbps" }), ref: "Handbook p.371" },
      { q: "Hartley channel capacity for noiseless 4 kHz channel, 8 levels:",
        choices: ["$24$ kbps", "$8$ kbps", "$32$ kbps", "$4$ kbps"], correct: 0,
        solution: S({ c: "Hartley: $C = 2B \\log_2 M$.", s: ["$C = 2(4000) \\log_2 8 = 8000 \\cdot 3 = 24000$ bps."], a: "$24$ kbps" }), ref: "Handbook p.371" },
      { q: "AM with carrier 1 MHz, modulation index $m = 1$ (full modulation):",
        choices: ["Sideband power equals 1/3 of total", "All power in carrier", "All in sidebands", "Equal split"], correct: 0,
        solution: S({ c: "$\\eta = m^2/(2+m^2) = 1/3$ for m=1.", s: ["Each sideband carries 1/6 of total power."], a: "1/3 of total in sidebands", v: "Why suppressed-carrier AM (DSB-SC) is more efficient." }), ref: "Handbook p.371" },
      { q: "Bandwidth of QPSK modulating bit stream at $R_b$ bps:",
        choices: ["$\\approx R_b/2$", "$\\approx R_b$", "$2 R_b$", "$4 R_b$"], correct: 0,
        solution: S({ c: "QPSK: 2 bits/symbol, symbol rate $R_b/2$. Bandwidth $\\approx$ symbol rate.", s: ["BPSK: BW $\\approx R_b$.", "16-QAM: BW $\\approx R_b/4$."], a: "$R_b/2$" }), ref: "Handbook p.371" },
      { q: "Hamming distance between 10110 and 11011:",
        choices: ["$3$", "$2$", "$5$", "$0$"], correct: 0,
        solution: S({ c: "Hamming distance: number of bit positions that differ.", s: ["10110", "11011", "Diff: pos 2, 4, 5 → 3 differences."], a: "$3$", v: "Codes with min Hamming distance $d$ can detect $d-1$ errors and correct $\\lfloor(d-1)/2\\rfloor$." }), ref: "Handbook p.371" },
      { q: "ASK modulation efficiency:",
        choices: ["Poor — wastes power in carrier", "Best", "Same as FSK", "Linear with $m$"], correct: 0,
        solution: S({ c: "ASK varies amplitude → wastes carrier power when transmitting 0 (or vice versa).", s: ["FSK / PSK have constant envelope — more efficient."], a: "Poor" }), ref: "Handbook p.371" },
      { q: "Why use modulation? Primary reason:",
        choices: ["Shift to higher frequency for antenna size, multiplexing", "Reduce signal power", "Increase bandwidth", "Smaller signals"], correct: 0,
        solution: S({ c: "Modulation: shifts baseband to carrier frequency. Allows: (1) practical antenna size, (2) FDM channel sharing, (3) better propagation at certain frequencies.", s: ["Antenna efficient size ≈ λ/4. At low freq, antennas would be impossibly large."], a: "Antenna size, multiplexing" }), ref: "Handbook p.371" },
      { q: "Shannon capacity: $C = B\\log_2(1 + S/N)$. Doubling B with same SNR:",
        choices: ["Doubles C", "Quadruples C", "Halves C", "No effect"], correct: 0,
        solution: S({ c: "Linear in B.", s: ["Doubling B → doubles C (SNR unchanged)."], a: "Doubles" }), ref: "Handbook p.371" },
      { q: "Manchester encoding: how many transitions per bit?",
        choices: ["Exactly 1 (mid-bit)", "0", "2", "Variable"], correct: 0,
        solution: S({ c: "Manchester: each bit period has transition in middle (encoding 0 or 1 by direction).", s: ["Pro: self-clocking, no DC offset.", "Con: doubles signal bandwidth."], a: "1 mid-bit transition" }), ref: "Handbook p.371" },
      { q: "TDMA, FDMA, CDMA differ by:",
        choices: ["Time slots, frequency bands, code separation", "Same thing", "Amplitude levels", "Phase angles"], correct: 0,
        solution: S({ c: "Multiple access methods for sharing channel.", s: ["TDMA: time slots (GSM 2G).", "FDMA: frequency bands (FM radio, AMPS).", "CDMA: spreading codes (CDMA2000, 3G)."], a: "Time, freq, code" }), ref: "Handbook p.371" },
    ],

    // ====================== Ch 14: Networks — +8 ======================
    14: [
      { q: "$/16$ subnet has __ usable hosts:",
        choices: ["$65{,}534$", "$65{,}536$", "$16{,}382$", "$254$"], correct: 0,
        solution: S({ c: "Host bits = 32 - 16 = 16. Total = $2^{16}$, usable = total - 2.", s: ["$65536 - 2 = 65534$."], a: "$65{,}534$" }), ref: "Handbook p.393" },
      { q: "Loopback IPv4 address:",
        choices: ["$127.0.0.1$", "$0.0.0.0$", "$255.255.255.255$", "$10.0.0.1$"], correct: 0,
        solution: S({ c: "Loopback: refers to local host. $127.0.0.0/8$ all reserved for loopback.", s: ["Doesn't leave the host's network stack.", "IPv6 loopback: ::1."], a: "$127.0.0.1$" }), ref: "Handbook p.394" },
      { q: "MAC address bits:",
        choices: ["$48$", "$32$", "$64$", "$128$"], correct: 0,
        solution: S({ c: "Standard IEEE MAC: 48 bits, usually 6 hex pairs.", s: ["First 3 bytes: OUI (organization).", "Last 3 bytes: vendor-assigned."], a: "$48$ bits" }), ref: "Handbook p.399" },
      { q: "Network packet routing decision is made at:",
        choices: ["L3 (Network) — IP", "L2 (Data link)", "L4 (Transport)", "L7 (Application)"], correct: 0,
        solution: S({ c: "Routers use IP (L3) to forward across networks.", s: ["Within local network: L2 (switches use MAC)."], a: "L3" }), ref: "Handbook p.399" },
      { q: "Default web port for HTTPS:",
        choices: ["$443$", "$80$", "$22$", "$25$"], correct: 0,
        solution: S({ c: "HTTPS = HTTP over TLS, standard on port 443.", s: ["HTTP: 80 (unencrypted)."], a: "$443$" }), ref: "Handbook p.394" },
      { q: "Subnet mask $255.255.255.0$ corresponds to CIDR:",
        choices: ["$/24$", "$/16$", "$/8$", "$/32$"], correct: 0,
        solution: S({ c: "$255 = 11111111_2 = 8$ ones each octet. Three full octets = 24 bits.", s: ["$255.255.255.0 = /24$."], a: "$/24$" }), ref: "Handbook p.393" },
      { q: "TCP 3-way handshake messages:",
        choices: ["SYN, SYN-ACK, ACK", "SYN, ACK, FIN", "GET, OK, BYE", "REQ, RESP, ACK"], correct: 0,
        solution: S({ c: "TCP connection: client SYN → server SYN-ACK → client ACK.", s: ["After handshake: data transfer with sequence numbers + ACKs."], a: "SYN, SYN-ACK, ACK" }), ref: "Handbook p.400" },
      { q: "Wireshark is:",
        choices: ["Network packet analyzer/sniffer", "Firewall", "VPN", "Router"], correct: 0,
        solution: S({ c: "Wireshark captures and dissects network traffic. Open-source.", s: ["Used for debugging, security analysis, learning protocols."], a: "Packet sniffer" }), ref: "Handbook p.412" },
    ],

    // ====================== Ch 15: Digital — +12 ======================
    15: [
      { q: "Binary 10001 in decimal:",
        choices: ["$17$", "$15$", "$19$", "$32$"], correct: 0,
        solution: S({ c: "Place values.", s: ["$16 + 0 + 0 + 0 + 1 = 17$."], a: "$17$" }), ref: "Handbook p.388" },
      { q: "Decimal 200 in binary:",
        choices: ["$11001000$", "$11000100$", "$10101010$", "$11111000$"], correct: 0,
        solution: S({ c: "Decompose.", s: ["$200 = 128 + 64 + 8 = 2^7+2^6+2^3$.", "Binary: 11001000."], a: "$11001000$" }), ref: "Handbook p.388" },
      { q: "$\\text{4A}_{16} + \\text{B5}_{16}$ = ?",
        choices: ["$\\text{FF}_{16}$", "$\\text{F0}_{16}$", "$\\text{100}_{16}$", "$\\text{AB}_{16}$"], correct: 0,
        solution: S({ c: "Convert to decimal, add, convert back.", s: ["4A = 74. B5 = 181. Sum = 255 = FF.", "Equivalently: 4 + B = F (15); A + 5 = F (15)."], a: "$\\text{FF}$" }), ref: "Handbook p.388" },
      { q: "How many minterms in a 4-variable Boolean function (max):",
        choices: ["$16$", "$4$", "$8$", "$32$"], correct: 0,
        solution: S({ c: "$2^n$ rows in truth table → up to $2^n$ minterms.", s: ["Each row could be 0 or 1; rows where output is 1 = minterms."], a: "$16$" }), ref: "Handbook p.389" },
      { q: "JK flip-flop with J=0, K=0:",
        choices: ["Hold", "Set", "Reset", "Toggle"], correct: 0,
        solution: S({ c: "JK truth table: 0,0=hold; 1,0=set; 0,1=reset; 1,1=toggle.", s: [""], a: "Hold" }), ref: "Handbook p.391" },
      { q: "SR latch input S=1, R=1 (simultaneously):",
        choices: ["Forbidden (indeterminate)", "Set", "Reset", "Toggle"], correct: 0,
        solution: S({ c: "Simultaneous S=R=1: both outputs forced HIGH → race condition when released.", s: ["JK FF resolves this by toggling instead."], a: "Forbidden" }), ref: "Handbook p.391" },
      { q: "Ripple carry adder for 4-bit numbers: number of full adders needed:",
        choices: ["$4$", "$8$", "$16$", "$3$"], correct: 0,
        solution: S({ c: "One full adder per bit position.", s: ["LSB can use half-adder if no carry in.", "MSB carries out as overflow."], a: "$4$ full adders" }), ref: "Handbook p.390" },
      { q: "Demultiplexer (1-to-N) with 4 outputs needs ___ select lines:",
        choices: ["$2$", "$4$", "$3$", "$1$"], correct: 0,
        solution: S({ c: "$\\log_2 N$ select lines.", s: ["$\\log_2 4 = 2$."], a: "$2$" }), ref: "Handbook p.390" },
      { q: "Bit-shift left by 1: equivalent to:",
        choices: ["Multiplying by 2", "Dividing by 2", "Adding 1", "Bit complement"], correct: 0,
        solution: S({ c: "$1010_2 \\to 10100_2$. $10_{10} \\to 20_{10}$.", s: ["Right shift = divide by 2.", "Arithmetic right shift preserves sign bit."], a: "$\\times 2$" }), ref: "Handbook p.389" },
      { q: "Tri-state buffer outputs:",
        choices: ["High, Low, or High-impedance", "Just High or Low", "Always Low", "Random"], correct: 0,
        solution: S({ c: "Tri-state has Enable input. When disabled: output is high-Z (effectively disconnected).", s: ["Allows multiple drivers on shared bus — only one active at a time."], a: "0, 1, or Hi-Z" }), ref: "Handbook p.391" },
      { q: "Convert 0.625 (decimal) to binary fraction:",
        choices: ["$0.101_2$", "$0.110_2$", "$0.011_2$", "$0.111_2$"], correct: 0,
        solution: S({ c: "Multiply by 2 repeatedly, collect integer parts.", s: ["$0.625 \\times 2 = 1.25$ → 1, keep 0.25.", "$0.25 \\times 2 = 0.5$ → 0, keep 0.5.", "$0.5 \\times 2 = 1.0$ → 1, done.", "Read: 0.101."], a: "$0.101_2$", v: "$1/2 + 1/8 = 0.5 + 0.125 = 0.625$ ✓" }), ref: "Handbook p.388" },
      { q: "Synchronous counter advantages over async ripple:",
        choices: ["No accumulated propagation delay, glitch-free", "Simpler", "Fewer connections", "Lower power"], correct: 0,
        solution: S({ c: "Sync: all FFs change on same clock edge → outputs change together.", s: ["Async ripple: each FF triggers next → delays add up, transient states appear.", "Sync more complex but reliable."], a: "No accumulated delay" }), ref: "Handbook p.391" },
    ],

    // ====================== Ch 16: CompSys — +12 ======================
    16: [
      { q: "ISA = ",
        choices: ["Instruction Set Architecture", "Internal System Address", "Industry Standard Adapter", "Internet Service Account"], correct: 0,
        solution: S({ c: "ISA = abstract interface between hardware and software. Defines available instructions, registers, addressing modes.", s: ["Examples: x86, ARM, RISC-V, MIPS."], a: "Instruction Set Architecture" }), ref: "Handbook p.408" },
      { q: "RISC vs CISC:",
        choices: ["RISC = simple uniform instructions; CISC = complex variable", "Same thing", "RISC is older", "CISC is faster"], correct: 0,
        solution: S({ c: "RISC: fixed-length instructions, load/store, register-based. CISC: variable-length, complex memory operations.", s: ["ARM, RISC-V, MIPS = RISC.", "x86 = CISC (though internally translates to micro-ops, blurring line)."], a: "RISC: simple; CISC: complex" }), ref: "Handbook p.408" },
      { q: "Cache hit time vs main memory access time:",
        choices: ["Cache much faster (10-100×)", "Same", "Cache slower", "Variable"], correct: 0,
        solution: S({ c: "L1 cache: 1-5 ns. Main memory (DRAM): 50-100 ns.", s: ["L2/L3 between.", "SSD: 25-100 µs (1000× slower).", "HDD: ms (1000× slower again)."], a: "10-100× faster" }), ref: "Handbook p.407" },
      { q: "Virtual memory provides:",
        choices: ["Per-process address space, more memory than physical", "Faster RAM", "Encryption", "Backup"], correct: 0,
        solution: S({ c: "VM: each process sees its own address space; OS+MMU translates to physical. Allows over-commit via paging to disk.", s: ["Page table entries map virtual to physical.", "TLB caches translations for speed."], a: "Process isolation + more memory" }), ref: "Handbook p.408" },
      { q: "Pipelining improves throughput, not necessarily:",
        choices: ["Individual instruction latency", "Total work", "Code complexity", "Memory usage"], correct: 0,
        solution: S({ c: "Each instruction takes same total time (or slightly more due to stage delays). But many overlap → higher throughput.", s: ["Latency: time for one instruction.", "Throughput: instructions per second."], a: "Latency unchanged" }), ref: "Handbook p.408" },
      { q: "Branch prediction misprediction penalty in deep pipeline:",
        choices: ["Many wasted cycles (flush + refetch)", "None", "1 cycle", "Random"], correct: 0,
        solution: S({ c: "Mispredicted branch → flush pipeline, fetch from correct address. Cost: pipeline depth.", s: ["Modern CPU: 15-20 cycles penalty.", "Why branch prediction (accuracy >95%) is so important."], a: "Cycles = pipeline depth" }), ref: "Handbook p.408" },
      { q: "SIMD (Single Instruction Multiple Data):",
        choices: ["Same op on multiple data simultaneously (vector ops)", "Multiple programs in parallel", "Memory replication", "Cache coherency"], correct: 0,
        solution: S({ c: "SIMD: one instruction operates on a vector of values in one cycle.", s: ["x86: MMX, SSE, AVX. ARM: NEON.", "Used in: graphics, scientific computing, ML."], a: "Vector operations" }), ref: "Handbook p.408" },
      { q: "GPU vs CPU:",
        choices: ["GPU: many simple cores (parallel); CPU: few complex cores (serial)", "Same", "GPU only graphics", "CPU is faster always"], correct: 0,
        solution: S({ c: "GPU: thousands of small cores, good for parallel/SIMD work. CPU: few cores, complex (branch prediction, caches).", s: ["GPU excels: graphics, ML, simulations.", "CPU excels: branching code, single-threaded tasks."], a: "GPU parallel; CPU serial+complex" }), ref: "Handbook p.408" },
      { q: "Stack pointer points to:",
        choices: ["Top of stack (most recent push)", "Bottom of stack", "Middle", "Heap"], correct: 0,
        solution: S({ c: "SP register tracks the next free stack slot (or current top).", s: ["Stack typically grows downward (toward lower addresses).", "Push: SP decreases, then write. Pop: read, then SP increases."], a: "Top of stack" }), ref: "Handbook p.408" },
      { q: "Interrupt vs polling:",
        choices: ["Interrupt: device notifies CPU; Polling: CPU checks", "Same", "Polling is faster", "Interrupt is older"], correct: 0,
        solution: S({ c: "Interrupt: hardware signals CPU on event → CPU handles. Polling: CPU periodically checks status.", s: ["Interrupts: efficient for rare events.", "Polling: simpler, useful for high-rate events."], a: "Interrupt vs poll" }), ref: "Handbook p.408" },
      { q: "ARM vs x86: ARM is generally:",
        choices: ["Lower power, RISC, dominant in mobile", "Older", "Faster on desktop", "Cheaper to license"], correct: 0,
        solution: S({ c: "ARM: low power consumption, RISC architecture. Used in: phones, tablets, embedded systems, Apple Silicon Macs.", s: ["x86: higher performance per-thread historically, more complex.", "ARM gaining server share too (AWS Graviton)."], a: "Lower power, mobile-focused" }), ref: "Handbook p.408" },
      { q: "Word size of a 32-bit processor:",
        choices: ["$32$ bits", "$32$ bytes", "$4$ bits", "$8$ bits"], correct: 0,
        solution: S({ c: "Word size = natural unit of data processing.", s: ["32-bit: 4-byte word, 32-bit address space (≤4 GB).", "64-bit: 8-byte word, huge address space."], a: "$32$ bits" }), ref: "Handbook p.407" },
    ],

    // ====================== Ch 17: Software — +8 ======================
    17: [
      { q: "Big-O of accessing array index $a[i]$:",
        choices: ["$O(1)$", "$O(n)$", "$O(\\log n)$", "$O(n^2)$"], correct: 0,
        solution: S({ c: "Array random access: constant time via pointer arithmetic.", s: ["Linked list access: $O(n)$ — must traverse from head."], a: "$O(1)$" }), ref: "Handbook p.415" },
      { q: "Inserting into sorted array at correct position:",
        choices: ["$O(n)$ — shift elements", "$O(1)$", "$O(\\log n)$", "$O(n^2)$"], correct: 0,
        solution: S({ c: "Find position (binary search): $O(\\log n)$. Shift remaining: $O(n)$. Total: $O(n)$.", s: ["Linked list version: insertion $O(1)$ if you have pointer to spot."], a: "$O(n)$" }), ref: "Handbook p.415" },
      { q: "Recursion uses ___ data structure (implicit):",
        choices: ["Stack", "Queue", "Heap", "Array"], correct: 0,
        solution: S({ c: "Each recursive call adds a frame to call stack.", s: ["LIFO: most recent call returns first.", "Stack overflow: too deep recursion exhausts stack memory."], a: "Stack" }), ref: "Handbook p.415" },
      { q: "Heap data structure (binary heap):",
        choices: ["Tree where parent ≤ children (min-heap)", "Linear array", "Hashtable", "Stack"], correct: 0,
        solution: S({ c: "Heap: complete binary tree with heap property.", s: ["Min-heap: parent ≤ children → root is minimum.", "Max-heap: parent ≥ children → root is max.", "Implemented as array (parent at $i/2$, children at $2i$ and $2i+1$)."], a: "Tree with order property" }), ref: "Handbook p.415" },
      { q: "Priority queue typically implemented as:",
        choices: ["Heap (O(log n) operations)", "Stack", "Array", "Linked list"], correct: 0,
        solution: S({ c: "Heap: insert $O(\\log n)$, extract-min $O(\\log n)$. Used for: Dijkstra's algorithm, A* search, OS task scheduling.", s: ["Array-based: $O(n)$ insert OR extract.", "Sorted array: insert $O(n)$, extract $O(1)$."], a: "Heap" }), ref: "Handbook p.415" },
      { q: "Memory allocated on heap vs stack: difference:",
        choices: ["Heap: dynamic, programmer-managed; Stack: automatic, function-local", "Same", "Heap is faster", "Stack is unlimited"], correct: 0,
        solution: S({ c: "Stack: automatic (function variables), fast, LIFO, limited size. Heap: dynamic (malloc/new), flexible size, slower allocation, programmer must free.", s: ["Memory leaks: heap memory not freed.", "Stack overflow: too deep recursion / too large stack frames."], a: "Heap dynamic; Stack automatic" }), ref: "Handbook p.415" },
      { q: "Big-O of Hash table worst case (with collisions):",
        choices: ["$O(n)$", "$O(1)$", "$O(\\log n)$", "$O(n^2)$"], correct: 0,
        solution: S({ c: "Worst case: all keys collide into one bucket → linear search.", s: ["Good hash + reasonable load: average O(1).", "Modern implementations resize when load > threshold."], a: "$O(n)$ worst" }), ref: "Handbook p.415" },
      { q: "Time complexity of finding max in unsorted array of n elements:",
        choices: ["$O(n)$", "$O(1)$", "$O(\\log n)$", "$O(n^2)$"], correct: 0,
        solution: S({ c: "Must examine every element to be sure max wasn't somewhere later.", s: ["Sorted array: O(1) — max is last element.", "Heap: O(1) for max-heap."], a: "$O(n)$" }), ref: "Handbook p.415" },
    ],
  };

  let added = 0;
  for (const ch of QUESTION_BANK.chapters) {
    if (P[ch.id]) {
      ch.questions.push(...P[ch.id]);
      added += P[ch.id].length;
    }
  }
  const total = QUESTION_BANK.chapters.reduce((s, c) => s + c.questions.length, 0);
  console.log(`Pack 4: +${added} → bank total ${total}`);
})();
